#![allow(dead_code)]

//! GENERATED by tools/p3-table-gen — the p3 WASI import table.
//! Derived from dovetail/wit/wasi-p3-*.wit via wit-parser wasm_signature.
//! Regenerate with `cargo run -p p3-table-gen > dovetail/src/compiler/codegen/p3_imports.rs`
//! if the WIT changes; do not hand-edit sigs.

use wasm_encoder::ValType;

pub struct P3Import {
    pub module: &'static str,
    pub name: &'static str,
    pub params: &'static [ValType],
    pub results: &'static [ValType],
}

/// waitable-set.new — $root
pub const FUNC_P3_ROOT_WAITABLE_SET_NEW: u32 = 0;
/// waitable-set.wait(set, retptr) -> event — $root
pub const FUNC_P3_ROOT_WAITABLE_SET_WAIT: u32 = 1;
/// waitable-set.drop — $root
pub const FUNC_P3_ROOT_WAITABLE_SET_DROP: u32 = 2;
/// waitable.join(waitable, set) — $root
pub const FUNC_P3_ROOT_WAITABLE_JOIN: u32 = 3;
/// subtask.drop — $root
pub const FUNC_P3_ROOT_SUBTASK_DROP: u32 = 4;
/// subtask.cancel -> status — $root
pub const FUNC_P3_ROOT_SUBTASK_CANCEL: u32 = 5;
/// get-environment — wasi:cli/environment@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_ENVIRONMENT_GET_ENVIRONMENT: u32 = 6;
/// get-arguments — wasi:cli/environment@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_ENVIRONMENT_GET_ARGUMENTS: u32 = 7;
/// get-initial-cwd — wasi:cli/environment@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_ENVIRONMENT_GET_INITIAL_CWD: u32 = 8;
/// exit — wasi:cli/exit@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_EXIT_EXIT: u32 = 9;
/// read-via-stream — wasi:cli/stdin@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDIN_READ_VIA_STREAM: u32 = 10;
/// read-via-stream : stream<u8> — wasi:cli/stdin@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDIN_STREAM_CANCEL_READ_0_READ_VIA_STREAM: u32 = 11;
/// read-via-stream : stream<u8> — wasi:cli/stdin@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDIN_STREAM_DROP_READABLE_0_READ_VIA_STREAM: u32 = 12;
/// read-via-stream : stream<u8> — wasi:cli/stdin@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDIN_ASYNC_STREAM_READ_0_READ_VIA_STREAM: u32 = 13;
/// read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 87 })) })> — wasi:cli/stdin@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDIN_FUTURE_CANCEL_READ_1_READ_VIA_STREAM: u32 = 14;
/// read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 87 })) })> — wasi:cli/stdin@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDIN_FUTURE_DROP_READABLE_1_READ_VIA_STREAM: u32 = 15;
/// read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 87 })) })> — wasi:cli/stdin@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDIN_ASYNC_FUTURE_READ_1_READ_VIA_STREAM: u32 = 16;
/// write-via-stream — wasi:cli/stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDOUT_WRITE_VIA_STREAM: u32 = 17;
/// write-via-stream : stream<u8> — wasi:cli/stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDOUT_STREAM_NEW_0_WRITE_VIA_STREAM: u32 = 18;
/// write-via-stream : stream<u8> — wasi:cli/stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDOUT_STREAM_CANCEL_WRITE_0_WRITE_VIA_STREAM: u32 = 19;
/// write-via-stream : stream<u8> — wasi:cli/stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDOUT_STREAM_DROP_WRITABLE_0_WRITE_VIA_STREAM: u32 = 20;
/// write-via-stream : stream<u8> — wasi:cli/stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDOUT_STREAM_DROP_READABLE_0_WRITE_VIA_STREAM: u32 = 21;
/// write-via-stream : stream<u8> — wasi:cli/stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDOUT_ASYNC_STREAM_WRITE_0_WRITE_VIA_STREAM: u32 = 22;
/// write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 92 })) })> — wasi:cli/stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDOUT_FUTURE_CANCEL_READ_1_WRITE_VIA_STREAM: u32 = 23;
/// write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 92 })) })> — wasi:cli/stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDOUT_FUTURE_DROP_READABLE_1_WRITE_VIA_STREAM: u32 = 24;
/// write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 92 })) })> — wasi:cli/stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDOUT_ASYNC_FUTURE_READ_1_WRITE_VIA_STREAM: u32 = 25;
/// write-via-stream — wasi:cli/stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDERR_WRITE_VIA_STREAM: u32 = 26;
/// write-via-stream : stream<u8> — wasi:cli/stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDERR_STREAM_NEW_0_WRITE_VIA_STREAM: u32 = 27;
/// write-via-stream : stream<u8> — wasi:cli/stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDERR_STREAM_CANCEL_WRITE_0_WRITE_VIA_STREAM: u32 = 28;
/// write-via-stream : stream<u8> — wasi:cli/stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDERR_STREAM_DROP_WRITABLE_0_WRITE_VIA_STREAM: u32 = 29;
/// write-via-stream : stream<u8> — wasi:cli/stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDERR_STREAM_DROP_READABLE_0_WRITE_VIA_STREAM: u32 = 30;
/// write-via-stream : stream<u8> — wasi:cli/stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDERR_ASYNC_STREAM_WRITE_0_WRITE_VIA_STREAM: u32 = 31;
/// write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 95 })) })> — wasi:cli/stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDERR_FUTURE_CANCEL_READ_1_WRITE_VIA_STREAM: u32 = 32;
/// write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 95 })) })> — wasi:cli/stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDERR_FUTURE_DROP_READABLE_1_WRITE_VIA_STREAM: u32 = 33;
/// write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 95 })) })> — wasi:cli/stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_STDERR_ASYNC_FUTURE_READ_1_WRITE_VIA_STREAM: u32 = 34;
/// drop resource terminal-input — wasi:cli/terminal-input@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_TERMINAL_INPUT_DROP_TERMINAL_INPUT: u32 = 35;
/// drop resource terminal-output — wasi:cli/terminal-output@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_TERMINAL_OUTPUT_DROP_TERMINAL_OUTPUT: u32 = 36;
/// get-terminal-stdin — wasi:cli/terminal-stdin@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_TERMINAL_STDIN_GET_TERMINAL_STDIN: u32 = 37;
/// get-terminal-stdout — wasi:cli/terminal-stdout@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_TERMINAL_STDOUT_GET_TERMINAL_STDOUT: u32 = 38;
/// get-terminal-stderr — wasi:cli/terminal-stderr@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLI_TERMINAL_STDERR_GET_TERMINAL_STDERR: u32 = 39;
/// now — wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLOCKS_MONOTONIC_CLOCK_NOW: u32 = 40;
/// get-resolution — wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLOCKS_MONOTONIC_CLOCK_GET_RESOLUTION: u32 = 41;
/// wait-until (async) — wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLOCKS_MONOTONIC_CLOCK_ASYNC_WAIT_UNTIL: u32 = 42;
/// wait-for (async) — wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLOCKS_MONOTONIC_CLOCK_ASYNC_WAIT_FOR: u32 = 43;
/// now — wasi:clocks/system-clock@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLOCKS_SYSTEM_CLOCK_NOW: u32 = 44;
/// get-resolution — wasi:clocks/system-clock@0.3.0-rc-2026-03-15
pub const FUNC_P3_CLOCKS_SYSTEM_CLOCK_GET_RESOLUTION: u32 = 45;
/// [method]descriptor.read-via-stream — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_METHOD_DESCRIPTOR_READ_VIA_STREAM: u32 = 46;
/// [method]descriptor.read-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_CANCEL_READ_0_METHOD_DESCRIPTOR_READ_VIA_STREAM: u32 = 47;
/// [method]descriptor.read-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_DROP_READABLE_0_METHOD_DESCRIPTOR_READ_VIA_STREAM: u32 = 48;
/// [method]descriptor.read-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_STREAM_READ_0_METHOD_DESCRIPTOR_READ_VIA_STREAM: u32 = 49;
/// [method]descriptor.read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_FUTURE_CANCEL_READ_1_METHOD_DESCRIPTOR_READ_VIA_STREAM: u32 = 50;
/// [method]descriptor.read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_FUTURE_DROP_READABLE_1_METHOD_DESCRIPTOR_READ_VIA_STREAM: u32 = 51;
/// [method]descriptor.read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_FUTURE_READ_1_METHOD_DESCRIPTOR_READ_VIA_STREAM: u32 = 52;
/// [method]descriptor.write-via-stream — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_METHOD_DESCRIPTOR_WRITE_VIA_STREAM: u32 = 53;
/// [method]descriptor.write-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_NEW_0_METHOD_DESCRIPTOR_WRITE_VIA_STREAM: u32 = 54;
/// [method]descriptor.write-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_CANCEL_WRITE_0_METHOD_DESCRIPTOR_WRITE_VIA_STREAM: u32 = 55;
/// [method]descriptor.write-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_DROP_WRITABLE_0_METHOD_DESCRIPTOR_WRITE_VIA_STREAM: u32 = 56;
/// [method]descriptor.write-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_DROP_READABLE_0_METHOD_DESCRIPTOR_WRITE_VIA_STREAM: u32 = 57;
/// [method]descriptor.write-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_STREAM_WRITE_0_METHOD_DESCRIPTOR_WRITE_VIA_STREAM: u32 = 58;
/// [method]descriptor.write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_FUTURE_CANCEL_READ_1_METHOD_DESCRIPTOR_WRITE_VIA_STREAM: u32 = 59;
/// [method]descriptor.write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_FUTURE_DROP_READABLE_1_METHOD_DESCRIPTOR_WRITE_VIA_STREAM: u32 = 60;
/// [method]descriptor.write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_FUTURE_READ_1_METHOD_DESCRIPTOR_WRITE_VIA_STREAM: u32 = 61;
/// [method]descriptor.append-via-stream — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_METHOD_DESCRIPTOR_APPEND_VIA_STREAM: u32 = 62;
/// [method]descriptor.append-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_NEW_0_METHOD_DESCRIPTOR_APPEND_VIA_STREAM: u32 = 63;
/// [method]descriptor.append-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_CANCEL_WRITE_0_METHOD_DESCRIPTOR_APPEND_VIA_STREAM: u32 = 64;
/// [method]descriptor.append-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_DROP_WRITABLE_0_METHOD_DESCRIPTOR_APPEND_VIA_STREAM: u32 = 65;
/// [method]descriptor.append-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_DROP_READABLE_0_METHOD_DESCRIPTOR_APPEND_VIA_STREAM: u32 = 66;
/// [method]descriptor.append-via-stream : stream<u8> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_STREAM_WRITE_0_METHOD_DESCRIPTOR_APPEND_VIA_STREAM: u32 = 67;
/// [method]descriptor.append-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_FUTURE_CANCEL_READ_1_METHOD_DESCRIPTOR_APPEND_VIA_STREAM: u32 = 68;
/// [method]descriptor.append-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_FUTURE_DROP_READABLE_1_METHOD_DESCRIPTOR_APPEND_VIA_STREAM: u32 = 69;
/// [method]descriptor.append-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_FUTURE_READ_1_METHOD_DESCRIPTOR_APPEND_VIA_STREAM: u32 = 70;
/// [method]descriptor.advise (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_ADVISE: u32 = 71;
/// [method]descriptor.sync-data (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_SYNC_DATA: u32 = 72;
/// [method]descriptor.get-flags (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_GET_FLAGS: u32 = 73;
/// [method]descriptor.get-type (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_GET_TYPE: u32 = 74;
/// [method]descriptor.set-size (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_SET_SIZE: u32 = 75;
/// [method]descriptor.set-times (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_SET_TIMES: u32 = 76;
/// [method]descriptor.read-directory — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_METHOD_DESCRIPTOR_READ_DIRECTORY: u32 = 77;
/// [method]descriptor.read-directory : stream<directory-entry> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_CANCEL_READ_0_METHOD_DESCRIPTOR_READ_DIRECTORY: u32 = 78;
/// [method]descriptor.read-directory : stream<directory-entry> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_STREAM_DROP_READABLE_0_METHOD_DESCRIPTOR_READ_DIRECTORY: u32 = 79;
/// [method]descriptor.read-directory : stream<directory-entry> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_STREAM_READ_0_METHOD_DESCRIPTOR_READ_DIRECTORY: u32 = 80;
/// [method]descriptor.read-directory : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_FUTURE_CANCEL_READ_1_METHOD_DESCRIPTOR_READ_DIRECTORY: u32 = 81;
/// [method]descriptor.read-directory : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_FUTURE_DROP_READABLE_1_METHOD_DESCRIPTOR_READ_DIRECTORY: u32 = 82;
/// [method]descriptor.read-directory : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })> — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_FUTURE_READ_1_METHOD_DESCRIPTOR_READ_DIRECTORY: u32 = 83;
/// [method]descriptor.sync (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_SYNC: u32 = 84;
/// [method]descriptor.create-directory-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_CREATE_DIRECTORY_AT: u32 = 85;
/// [method]descriptor.stat (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_STAT: u32 = 86;
/// [method]descriptor.stat-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_STAT_AT: u32 = 87;
/// [method]descriptor.set-times-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_SET_TIMES_AT: u32 = 88;
/// [method]descriptor.link-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_LINK_AT: u32 = 89;
/// [method]descriptor.open-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_OPEN_AT: u32 = 90;
/// [method]descriptor.readlink-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_READLINK_AT: u32 = 91;
/// [method]descriptor.remove-directory-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_REMOVE_DIRECTORY_AT: u32 = 92;
/// [method]descriptor.rename-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_RENAME_AT: u32 = 93;
/// [method]descriptor.symlink-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_SYMLINK_AT: u32 = 94;
/// [method]descriptor.unlink-file-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_UNLINK_FILE_AT: u32 = 95;
/// [method]descriptor.is-same-object (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_IS_SAME_OBJECT: u32 = 96;
/// [method]descriptor.metadata-hash (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_METADATA_HASH: u32 = 97;
/// [method]descriptor.metadata-hash-at (async) — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_ASYNC_METHOD_DESCRIPTOR_METADATA_HASH_AT: u32 = 98;
/// drop resource descriptor — wasi:filesystem/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_TYPES_DROP_DESCRIPTOR: u32 = 99;
/// get-directories — wasi:filesystem/preopens@0.3.0-rc-2026-03-15
pub const FUNC_P3_FILESYSTEM_PREOPENS_GET_DIRECTORIES: u32 = 100;
/// [static]tcp-socket.create — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STATIC_TCP_SOCKET_CREATE: u32 = 101;
/// [method]tcp-socket.bind — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_BIND: u32 = 102;
/// [method]tcp-socket.connect (async) — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_ASYNC_METHOD_TCP_SOCKET_CONNECT: u32 = 103;
/// [method]tcp-socket.listen — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_LISTEN: u32 = 104;
/// [method]tcp-socket.listen : stream<Handle(Own(Id { idx: 51 }))> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STREAM_CANCEL_READ_0_METHOD_TCP_SOCKET_LISTEN: u32 = 105;
/// [method]tcp-socket.listen : stream<Handle(Own(Id { idx: 51 }))> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STREAM_DROP_READABLE_0_METHOD_TCP_SOCKET_LISTEN: u32 = 106;
/// [method]tcp-socket.listen : stream<Handle(Own(Id { idx: 51 }))> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_ASYNC_STREAM_READ_0_METHOD_TCP_SOCKET_LISTEN: u32 = 107;
/// [method]tcp-socket.send — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_SEND: u32 = 108;
/// [method]tcp-socket.send : stream<u8> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STREAM_NEW_0_METHOD_TCP_SOCKET_SEND: u32 = 109;
/// [method]tcp-socket.send : stream<u8> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STREAM_CANCEL_WRITE_0_METHOD_TCP_SOCKET_SEND: u32 = 110;
/// [method]tcp-socket.send : stream<u8> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STREAM_DROP_WRITABLE_0_METHOD_TCP_SOCKET_SEND: u32 = 111;
/// [method]tcp-socket.send : stream<u8> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STREAM_DROP_READABLE_0_METHOD_TCP_SOCKET_SEND: u32 = 112;
/// [method]tcp-socket.send : stream<u8> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_ASYNC_STREAM_WRITE_0_METHOD_TCP_SOCKET_SEND: u32 = 113;
/// [method]tcp-socket.send : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_FUTURE_CANCEL_READ_1_METHOD_TCP_SOCKET_SEND: u32 = 114;
/// [method]tcp-socket.send : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_FUTURE_DROP_READABLE_1_METHOD_TCP_SOCKET_SEND: u32 = 115;
/// [method]tcp-socket.send : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_ASYNC_FUTURE_READ_1_METHOD_TCP_SOCKET_SEND: u32 = 116;
/// [method]tcp-socket.receive — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_RECEIVE: u32 = 117;
/// [method]tcp-socket.receive : stream<u8> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STREAM_CANCEL_READ_0_METHOD_TCP_SOCKET_RECEIVE: u32 = 118;
/// [method]tcp-socket.receive : stream<u8> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STREAM_DROP_READABLE_0_METHOD_TCP_SOCKET_RECEIVE: u32 = 119;
/// [method]tcp-socket.receive : stream<u8> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_ASYNC_STREAM_READ_0_METHOD_TCP_SOCKET_RECEIVE: u32 = 120;
/// [method]tcp-socket.receive : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_FUTURE_CANCEL_READ_1_METHOD_TCP_SOCKET_RECEIVE: u32 = 121;
/// [method]tcp-socket.receive : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_FUTURE_DROP_READABLE_1_METHOD_TCP_SOCKET_RECEIVE: u32 = 122;
/// [method]tcp-socket.receive : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })> — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_ASYNC_FUTURE_READ_1_METHOD_TCP_SOCKET_RECEIVE: u32 = 123;
/// [method]tcp-socket.get-local-address — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_LOCAL_ADDRESS: u32 = 124;
/// [method]tcp-socket.get-remote-address — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_REMOTE_ADDRESS: u32 = 125;
/// [method]tcp-socket.get-is-listening — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_IS_LISTENING: u32 = 126;
/// [method]tcp-socket.get-address-family — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_ADDRESS_FAMILY: u32 = 127;
/// [method]tcp-socket.set-listen-backlog-size — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_SET_LISTEN_BACKLOG_SIZE: u32 = 128;
/// [method]tcp-socket.get-keep-alive-enabled — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_KEEP_ALIVE_ENABLED: u32 = 129;
/// [method]tcp-socket.set-keep-alive-enabled — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_SET_KEEP_ALIVE_ENABLED: u32 = 130;
/// [method]tcp-socket.get-keep-alive-idle-time — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_KEEP_ALIVE_IDLE_TIME: u32 = 131;
/// [method]tcp-socket.set-keep-alive-idle-time — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_SET_KEEP_ALIVE_IDLE_TIME: u32 = 132;
/// [method]tcp-socket.get-keep-alive-interval — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_KEEP_ALIVE_INTERVAL: u32 = 133;
/// [method]tcp-socket.set-keep-alive-interval — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_SET_KEEP_ALIVE_INTERVAL: u32 = 134;
/// [method]tcp-socket.get-keep-alive-count — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_KEEP_ALIVE_COUNT: u32 = 135;
/// [method]tcp-socket.set-keep-alive-count — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_SET_KEEP_ALIVE_COUNT: u32 = 136;
/// [method]tcp-socket.get-hop-limit — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_HOP_LIMIT: u32 = 137;
/// [method]tcp-socket.set-hop-limit — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_SET_HOP_LIMIT: u32 = 138;
/// [method]tcp-socket.get-receive-buffer-size — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_RECEIVE_BUFFER_SIZE: u32 = 139;
/// [method]tcp-socket.set-receive-buffer-size — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_SET_RECEIVE_BUFFER_SIZE: u32 = 140;
/// [method]tcp-socket.get-send-buffer-size — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_GET_SEND_BUFFER_SIZE: u32 = 141;
/// [method]tcp-socket.set-send-buffer-size — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_TCP_SOCKET_SET_SEND_BUFFER_SIZE: u32 = 142;
/// [static]udp-socket.create — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_STATIC_UDP_SOCKET_CREATE: u32 = 143;
/// [method]udp-socket.bind — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_BIND: u32 = 144;
/// [method]udp-socket.connect — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_CONNECT: u32 = 145;
/// [method]udp-socket.disconnect — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_DISCONNECT: u32 = 146;
/// [method]udp-socket.send (async) — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_ASYNC_METHOD_UDP_SOCKET_SEND: u32 = 147;
/// [method]udp-socket.receive (async) — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_ASYNC_METHOD_UDP_SOCKET_RECEIVE: u32 = 148;
/// [method]udp-socket.get-local-address — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_GET_LOCAL_ADDRESS: u32 = 149;
/// [method]udp-socket.get-remote-address — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_GET_REMOTE_ADDRESS: u32 = 150;
/// [method]udp-socket.get-address-family — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_GET_ADDRESS_FAMILY: u32 = 151;
/// [method]udp-socket.get-unicast-hop-limit — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_GET_UNICAST_HOP_LIMIT: u32 = 152;
/// [method]udp-socket.set-unicast-hop-limit — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_SET_UNICAST_HOP_LIMIT: u32 = 153;
/// [method]udp-socket.get-receive-buffer-size — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_GET_RECEIVE_BUFFER_SIZE: u32 = 154;
/// [method]udp-socket.set-receive-buffer-size — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_SET_RECEIVE_BUFFER_SIZE: u32 = 155;
/// [method]udp-socket.get-send-buffer-size — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_GET_SEND_BUFFER_SIZE: u32 = 156;
/// [method]udp-socket.set-send-buffer-size — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_METHOD_UDP_SOCKET_SET_SEND_BUFFER_SIZE: u32 = 157;
/// drop resource tcp-socket — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_DROP_TCP_SOCKET: u32 = 158;
/// drop resource udp-socket — wasi:sockets/types@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_TYPES_DROP_UDP_SOCKET: u32 = 159;
/// resolve-addresses (async) — wasi:sockets/ip-name-lookup@0.3.0-rc-2026-03-15
pub const FUNC_P3_SOCKETS_IP_NAME_LOOKUP_ASYNC_RESOLVE_ADDRESSES: u32 = 160;
/// get-random-bytes — wasi:random/random@0.3.0-rc-2026-03-15
pub const FUNC_P3_RANDOM_RANDOM_GET_RANDOM_BYTES: u32 = 161;
/// get-random-u64 — wasi:random/random@0.3.0-rc-2026-03-15
pub const FUNC_P3_RANDOM_RANDOM_GET_RANDOM_U64: u32 = 162;
/// get-insecure-random-bytes — wasi:random/insecure@0.3.0-rc-2026-03-15
pub const FUNC_P3_RANDOM_INSECURE_GET_INSECURE_RANDOM_BYTES: u32 = 163;
/// get-insecure-random-u64 — wasi:random/insecure@0.3.0-rc-2026-03-15
pub const FUNC_P3_RANDOM_INSECURE_GET_INSECURE_RANDOM_U64: u32 = 164;
/// get-insecure-seed — wasi:random/insecure-seed@0.3.0-rc-2026-03-15
pub const FUNC_P3_RANDOM_INSECURE_SEED_GET_INSECURE_SEED: u32 = 165;
/// waitable-set.poll(set, retptr) -> event, or zero — $root
pub const FUNC_P3_ROOT_WAITABLE_SET_POLL: u32 = 166;
/// thread.yield -> cancellation status — $root
pub const FUNC_P3_ROOT_THREAD_YIELD: u32 = 167;

pub const NUM_P3_IMPORTS: u32 = 168;

pub const P3_IMPORTS: &[P3Import] = &[
    // waitable-set.new
    P3Import { module: "$root", name: "[waitable-set-new]", params: &[], results: &[ValType::I32] },
    // waitable-set.wait(set, retptr) -> event
    P3Import { module: "$root", name: "[waitable-set-wait]", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // waitable-set.drop
    P3Import { module: "$root", name: "[waitable-set-drop]", params: &[ValType::I32], results: &[] },
    // waitable.join(waitable, set)
    P3Import { module: "$root", name: "[waitable-join]", params: &[ValType::I32, ValType::I32], results: &[] },
    // subtask.drop
    P3Import { module: "$root", name: "[subtask-drop]", params: &[ValType::I32], results: &[] },
    // subtask.cancel -> status
    P3Import { module: "$root", name: "[subtask-cancel]", params: &[ValType::I32], results: &[ValType::I32] },
    // get-environment
    P3Import { module: "wasi:cli/environment@0.3.0-rc-2026-03-15", name: "get-environment", params: &[ValType::I32], results: &[] },
    // get-arguments
    P3Import { module: "wasi:cli/environment@0.3.0-rc-2026-03-15", name: "get-arguments", params: &[ValType::I32], results: &[] },
    // get-initial-cwd
    P3Import { module: "wasi:cli/environment@0.3.0-rc-2026-03-15", name: "get-initial-cwd", params: &[ValType::I32], results: &[] },
    // exit
    P3Import { module: "wasi:cli/exit@0.3.0-rc-2026-03-15", name: "exit", params: &[ValType::I32], results: &[] },
    // read-via-stream
    P3Import { module: "wasi:cli/stdin@0.3.0-rc-2026-03-15", name: "read-via-stream", params: &[ValType::I32], results: &[] },
    // read-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stdin@0.3.0-rc-2026-03-15", name: "[stream-cancel-read-0]read-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // read-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stdin@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0]read-via-stream", params: &[ValType::I32], results: &[] },
    // read-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stdin@0.3.0-rc-2026-03-15", name: "[async-lower][stream-read-0]read-via-stream", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 87 })) })>
    P3Import { module: "wasi:cli/stdin@0.3.0-rc-2026-03-15", name: "[future-cancel-read-1]read-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 87 })) })>
    P3Import { module: "wasi:cli/stdin@0.3.0-rc-2026-03-15", name: "[future-drop-readable-1]read-via-stream", params: &[ValType::I32], results: &[] },
    // read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 87 })) })>
    P3Import { module: "wasi:cli/stdin@0.3.0-rc-2026-03-15", name: "[async-lower][future-read-1]read-via-stream", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // write-via-stream
    P3Import { module: "wasi:cli/stdout@0.3.0-rc-2026-03-15", name: "write-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stdout@0.3.0-rc-2026-03-15", name: "[stream-new-0]write-via-stream", params: &[], results: &[ValType::I64] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stdout@0.3.0-rc-2026-03-15", name: "[stream-cancel-write-0]write-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stdout@0.3.0-rc-2026-03-15", name: "[stream-drop-writable-0]write-via-stream", params: &[ValType::I32], results: &[] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stdout@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0]write-via-stream", params: &[ValType::I32], results: &[] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stdout@0.3.0-rc-2026-03-15", name: "[async-lower][stream-write-0]write-via-stream", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 92 })) })>
    P3Import { module: "wasi:cli/stdout@0.3.0-rc-2026-03-15", name: "[future-cancel-read-1]write-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 92 })) })>
    P3Import { module: "wasi:cli/stdout@0.3.0-rc-2026-03-15", name: "[future-drop-readable-1]write-via-stream", params: &[ValType::I32], results: &[] },
    // write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 92 })) })>
    P3Import { module: "wasi:cli/stdout@0.3.0-rc-2026-03-15", name: "[async-lower][future-read-1]write-via-stream", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // write-via-stream
    P3Import { module: "wasi:cli/stderr@0.3.0-rc-2026-03-15", name: "write-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stderr@0.3.0-rc-2026-03-15", name: "[stream-new-0]write-via-stream", params: &[], results: &[ValType::I64] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stderr@0.3.0-rc-2026-03-15", name: "[stream-cancel-write-0]write-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stderr@0.3.0-rc-2026-03-15", name: "[stream-drop-writable-0]write-via-stream", params: &[ValType::I32], results: &[] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stderr@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0]write-via-stream", params: &[ValType::I32], results: &[] },
    // write-via-stream : stream<u8>
    P3Import { module: "wasi:cli/stderr@0.3.0-rc-2026-03-15", name: "[async-lower][stream-write-0]write-via-stream", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 95 })) })>
    P3Import { module: "wasi:cli/stderr@0.3.0-rc-2026-03-15", name: "[future-cancel-read-1]write-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 95 })) })>
    P3Import { module: "wasi:cli/stderr@0.3.0-rc-2026-03-15", name: "[future-drop-readable-1]write-via-stream", params: &[ValType::I32], results: &[] },
    // write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 95 })) })>
    P3Import { module: "wasi:cli/stderr@0.3.0-rc-2026-03-15", name: "[async-lower][future-read-1]write-via-stream", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // drop resource terminal-input
    P3Import { module: "wasi:cli/terminal-input@0.3.0-rc-2026-03-15", name: "[resource-drop]terminal-input", params: &[ValType::I32], results: &[] },
    // drop resource terminal-output
    P3Import { module: "wasi:cli/terminal-output@0.3.0-rc-2026-03-15", name: "[resource-drop]terminal-output", params: &[ValType::I32], results: &[] },
    // get-terminal-stdin
    P3Import { module: "wasi:cli/terminal-stdin@0.3.0-rc-2026-03-15", name: "get-terminal-stdin", params: &[ValType::I32], results: &[] },
    // get-terminal-stdout
    P3Import { module: "wasi:cli/terminal-stdout@0.3.0-rc-2026-03-15", name: "get-terminal-stdout", params: &[ValType::I32], results: &[] },
    // get-terminal-stderr
    P3Import { module: "wasi:cli/terminal-stderr@0.3.0-rc-2026-03-15", name: "get-terminal-stderr", params: &[ValType::I32], results: &[] },
    // now
    P3Import { module: "wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15", name: "now", params: &[], results: &[ValType::I64] },
    // get-resolution
    P3Import { module: "wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15", name: "get-resolution", params: &[], results: &[ValType::I64] },
    // wait-until (async)
    P3Import { module: "wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15", name: "[async-lower]wait-until", params: &[ValType::I64], results: &[ValType::I32] },
    // wait-for (async)
    P3Import { module: "wasi:clocks/monotonic-clock@0.3.0-rc-2026-03-15", name: "[async-lower]wait-for", params: &[ValType::I64], results: &[ValType::I32] },
    // now
    P3Import { module: "wasi:clocks/system-clock@0.3.0-rc-2026-03-15", name: "now", params: &[ValType::I32], results: &[] },
    // get-resolution
    P3Import { module: "wasi:clocks/system-clock@0.3.0-rc-2026-03-15", name: "get-resolution", params: &[], results: &[ValType::I64] },
    // [method]descriptor.read-via-stream
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[method]descriptor.read-via-stream", params: &[ValType::I32, ValType::I64, ValType::I32], results: &[] },
    // [method]descriptor.read-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-cancel-read-0][method]descriptor.read-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.read-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0][method]descriptor.read-via-stream", params: &[ValType::I32], results: &[] },
    // [method]descriptor.read-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][stream-read-0][method]descriptor.read-via-stream", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[future-cancel-read-1][method]descriptor.read-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[future-drop-readable-1][method]descriptor.read-via-stream", params: &[ValType::I32], results: &[] },
    // [method]descriptor.read-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][future-read-1][method]descriptor.read-via-stream", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.write-via-stream
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[method]descriptor.write-via-stream", params: &[ValType::I32, ValType::I32, ValType::I64], results: &[ValType::I32] },
    // [method]descriptor.write-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-new-0][method]descriptor.write-via-stream", params: &[], results: &[ValType::I64] },
    // [method]descriptor.write-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-cancel-write-0][method]descriptor.write-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.write-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-drop-writable-0][method]descriptor.write-via-stream", params: &[ValType::I32], results: &[] },
    // [method]descriptor.write-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0][method]descriptor.write-via-stream", params: &[ValType::I32], results: &[] },
    // [method]descriptor.write-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][stream-write-0][method]descriptor.write-via-stream", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[future-cancel-read-1][method]descriptor.write-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[future-drop-readable-1][method]descriptor.write-via-stream", params: &[ValType::I32], results: &[] },
    // [method]descriptor.write-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][future-read-1][method]descriptor.write-via-stream", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.append-via-stream
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[method]descriptor.append-via-stream", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.append-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-new-0][method]descriptor.append-via-stream", params: &[], results: &[ValType::I64] },
    // [method]descriptor.append-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-cancel-write-0][method]descriptor.append-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.append-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-drop-writable-0][method]descriptor.append-via-stream", params: &[ValType::I32], results: &[] },
    // [method]descriptor.append-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0][method]descriptor.append-via-stream", params: &[ValType::I32], results: &[] },
    // [method]descriptor.append-via-stream : stream<u8>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][stream-write-0][method]descriptor.append-via-stream", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.append-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[future-cancel-read-1][method]descriptor.append-via-stream", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.append-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[future-drop-readable-1][method]descriptor.append-via-stream", params: &[ValType::I32], results: &[] },
    // [method]descriptor.append-via-stream : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][future-read-1][method]descriptor.append-via-stream", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.advise (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.advise", params: &[ValType::I32, ValType::I64, ValType::I64, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.sync-data (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.sync-data", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.get-flags (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.get-flags", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.get-type (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.get-type", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.set-size (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.set-size", params: &[ValType::I32, ValType::I64, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.set-times (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.set-times", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.read-directory
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[method]descriptor.read-directory", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]descriptor.read-directory : stream<directory-entry>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-cancel-read-0][method]descriptor.read-directory", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.read-directory : stream<directory-entry>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0][method]descriptor.read-directory", params: &[ValType::I32], results: &[] },
    // [method]descriptor.read-directory : stream<directory-entry>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][stream-read-0][method]descriptor.read-directory", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.read-directory : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[future-cancel-read-1][method]descriptor.read-directory", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.read-directory : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[future-drop-readable-1][method]descriptor.read-directory", params: &[ValType::I32], results: &[] },
    // [method]descriptor.read-directory : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 19 })) })>
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][future-read-1][method]descriptor.read-directory", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.sync (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.sync", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.create-directory-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.create-directory-at", params: &[ValType::I32, ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.stat (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.stat", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.stat-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.stat-at", params: &[ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.set-times-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.set-times-at", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.link-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.link-at", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.open-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.open-at", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.readlink-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.readlink-at", params: &[ValType::I32, ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.remove-directory-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.remove-directory-at", params: &[ValType::I32, ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.rename-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.rename-at", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.symlink-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.symlink-at", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.unlink-file-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.unlink-file-at", params: &[ValType::I32, ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.is-same-object (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.is-same-object", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.metadata-hash (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.metadata-hash", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]descriptor.metadata-hash-at (async)
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]descriptor.metadata-hash-at", params: &[ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // drop resource descriptor
    P3Import { module: "wasi:filesystem/types@0.3.0-rc-2026-03-15", name: "[resource-drop]descriptor", params: &[ValType::I32], results: &[] },
    // get-directories
    P3Import { module: "wasi:filesystem/preopens@0.3.0-rc-2026-03-15", name: "get-directories", params: &[ValType::I32], results: &[] },
    // [static]tcp-socket.create
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[static]tcp-socket.create", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.bind
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.bind", params: &[ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.connect (async)
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]tcp-socket.connect", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.listen
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.listen", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.listen : stream<Handle(Own(Id { idx: 51 }))>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[stream-cancel-read-0][method]tcp-socket.listen", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.listen : stream<Handle(Own(Id { idx: 51 }))>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0][method]tcp-socket.listen", params: &[ValType::I32], results: &[] },
    // [method]tcp-socket.listen : stream<Handle(Own(Id { idx: 51 }))>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[async-lower][stream-read-0][method]tcp-socket.listen", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.send
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.send", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.send : stream<u8>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[stream-new-0][method]tcp-socket.send", params: &[], results: &[ValType::I64] },
    // [method]tcp-socket.send : stream<u8>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[stream-cancel-write-0][method]tcp-socket.send", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.send : stream<u8>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[stream-drop-writable-0][method]tcp-socket.send", params: &[ValType::I32], results: &[] },
    // [method]tcp-socket.send : stream<u8>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0][method]tcp-socket.send", params: &[ValType::I32], results: &[] },
    // [method]tcp-socket.send : stream<u8>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[async-lower][stream-write-0][method]tcp-socket.send", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.send : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[future-cancel-read-1][method]tcp-socket.send", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.send : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[future-drop-readable-1][method]tcp-socket.send", params: &[ValType::I32], results: &[] },
    // [method]tcp-socket.send : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[async-lower][future-read-1][method]tcp-socket.send", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.receive
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.receive", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.receive : stream<u8>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[stream-cancel-read-0][method]tcp-socket.receive", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.receive : stream<u8>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[stream-drop-readable-0][method]tcp-socket.receive", params: &[ValType::I32], results: &[] },
    // [method]tcp-socket.receive : stream<u8>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[async-lower][stream-read-0][method]tcp-socket.receive", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.receive : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[future-cancel-read-1][method]tcp-socket.receive", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.receive : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[future-drop-readable-1][method]tcp-socket.receive", params: &[ValType::I32], results: &[] },
    // [method]tcp-socket.receive : future<Result(Result_ { ok: None, err: Some(Id(Id { idx: 43 })) })>
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[async-lower][future-read-1][method]tcp-socket.receive", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.get-local-address
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-local-address", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.get-remote-address
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-remote-address", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.get-is-listening
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-is-listening", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.get-address-family
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-address-family", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]tcp-socket.set-listen-backlog-size
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.set-listen-backlog-size", params: &[ValType::I32, ValType::I64, ValType::I32], results: &[] },
    // [method]tcp-socket.get-keep-alive-enabled
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-keep-alive-enabled", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.set-keep-alive-enabled
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.set-keep-alive-enabled", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.get-keep-alive-idle-time
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-keep-alive-idle-time", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.set-keep-alive-idle-time
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.set-keep-alive-idle-time", params: &[ValType::I32, ValType::I64, ValType::I32], results: &[] },
    // [method]tcp-socket.get-keep-alive-interval
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-keep-alive-interval", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.set-keep-alive-interval
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.set-keep-alive-interval", params: &[ValType::I32, ValType::I64, ValType::I32], results: &[] },
    // [method]tcp-socket.get-keep-alive-count
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-keep-alive-count", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.set-keep-alive-count
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.set-keep-alive-count", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.get-hop-limit
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-hop-limit", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.set-hop-limit
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.set-hop-limit", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.get-receive-buffer-size
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-receive-buffer-size", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.set-receive-buffer-size
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.set-receive-buffer-size", params: &[ValType::I32, ValType::I64, ValType::I32], results: &[] },
    // [method]tcp-socket.get-send-buffer-size
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.get-send-buffer-size", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]tcp-socket.set-send-buffer-size
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]tcp-socket.set-send-buffer-size", params: &[ValType::I32, ValType::I64, ValType::I32], results: &[] },
    // [static]udp-socket.create
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[static]udp-socket.create", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.bind
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.bind", params: &[ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.connect
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.connect", params: &[ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.disconnect
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.disconnect", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.send (async)
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]udp-socket.send", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]udp-socket.receive (async)
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[async-lower][method]udp-socket.receive", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // [method]udp-socket.get-local-address
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.get-local-address", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.get-remote-address
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.get-remote-address", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.get-address-family
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.get-address-family", params: &[ValType::I32], results: &[ValType::I32] },
    // [method]udp-socket.get-unicast-hop-limit
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.get-unicast-hop-limit", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.set-unicast-hop-limit
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.set-unicast-hop-limit", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.get-receive-buffer-size
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.get-receive-buffer-size", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.set-receive-buffer-size
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.set-receive-buffer-size", params: &[ValType::I32, ValType::I64, ValType::I32], results: &[] },
    // [method]udp-socket.get-send-buffer-size
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.get-send-buffer-size", params: &[ValType::I32, ValType::I32], results: &[] },
    // [method]udp-socket.set-send-buffer-size
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[method]udp-socket.set-send-buffer-size", params: &[ValType::I32, ValType::I64, ValType::I32], results: &[] },
    // drop resource tcp-socket
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[resource-drop]tcp-socket", params: &[ValType::I32], results: &[] },
    // drop resource udp-socket
    P3Import { module: "wasi:sockets/types@0.3.0-rc-2026-03-15", name: "[resource-drop]udp-socket", params: &[ValType::I32], results: &[] },
    // resolve-addresses (async)
    P3Import { module: "wasi:sockets/ip-name-lookup@0.3.0-rc-2026-03-15", name: "[async-lower]resolve-addresses", params: &[ValType::I32, ValType::I32, ValType::I32], results: &[ValType::I32] },
    // get-random-bytes
    P3Import { module: "wasi:random/random@0.3.0-rc-2026-03-15", name: "get-random-bytes", params: &[ValType::I64, ValType::I32], results: &[] },
    // get-random-u64
    P3Import { module: "wasi:random/random@0.3.0-rc-2026-03-15", name: "get-random-u64", params: &[], results: &[ValType::I64] },
    // get-insecure-random-bytes
    P3Import { module: "wasi:random/insecure@0.3.0-rc-2026-03-15", name: "get-insecure-random-bytes", params: &[ValType::I64, ValType::I32], results: &[] },
    // get-insecure-random-u64
    P3Import { module: "wasi:random/insecure@0.3.0-rc-2026-03-15", name: "get-insecure-random-u64", params: &[], results: &[ValType::I64] },
    // get-insecure-seed
    P3Import { module: "wasi:random/insecure-seed@0.3.0-rc-2026-03-15", name: "get-insecure-seed", params: &[ValType::I32], results: &[] },
    // waitable-set.poll(set, retptr) -> event, or zero
    P3Import { module: "$root", name: "[waitable-set-poll]", params: &[ValType::I32, ValType::I32], results: &[ValType::I32] },
    // thread.yield -> cancellation status
    P3Import { module: "$root", name: "[thread-yield]", params: &[], results: &[ValType::I32] },
];

