mod class_constructors;
mod class_method_bounds;
mod extension_blocks;
mod implement_blocks;
pub(crate) mod substitute;

use std::collections::{BTreeMap, BTreeSet};

use crate::common::types::TypeParamName;
use crate::common::types::{Fqn, MangledName};
use crate::typechecker::registry::Registry;
use crate::typechecker::types::{
    Type, TypeDef, TypedExpr, TypedExprKind, TypedImplementBlock, TypedModule,
};

/// Cross-pass specialization must terminate even for polymorphic recursion that
/// alternates between an implementation and a generic helper while growing its type.
const MAX_SPECIALIZATION_ROUNDS: usize = 256;

#[derive(Debug)]
pub struct SpecializationError {
    pub span: crate::common::span::Span,
    pub message: String,
}

#[derive(Default)]
struct SpecializationRounds(usize);

impl SpecializationRounds {
    fn advance(&mut self, function: &TypedFunction) -> Result<(), SpecializationError> {
        self.0 += 1;
        if self.0 > MAX_SPECIALIZATION_ROUNDS {
            return Err(SpecializationError {
                span: function.span.clone(),
                message: format!(
                    "specialization limit exceeded after {MAX_SPECIALIZATION_ROUNDS} rounds while instantiating '{}'; recursive generic calls may keep growing their argument types",
                    function.source_name
                ),
            });
        }
        Ok(())
    }

    fn advance_for_new_functions(
        &mut self,
        module: &TypedModule,
        previous_names: &BTreeSet<MangledName>,
    ) -> Result<(), SpecializationError> {
        if let Some((_, function)) = module
            .functions
            .iter()
            .find(|(name, _)| !previous_names.contains(*name))
        {
            self.advance(function)?;
        }
        Ok(())
    }
}

pub fn monomorphize(
    mut module: TypedModule,
    registry: &Registry,
) -> Result<TypedModule, SpecializationError> {
    let normalization = crate::typechecker::associated_types::NormalizationScope::install(registry);
    implement_blocks::inject_default_members(&mut module, registry);
    implement_blocks::materialize_class_default_members(&mut module, registry);
    class_constructors::lower_generic_constructors(&mut module, registry);
    implement_blocks::expand_non_generic_impl_blocks(&mut module);
    extension_blocks::expand_non_generic_ext_blocks(&mut module);
    implement_blocks::resolve_impl_calls(&mut module, registry)?;
    extension_blocks::resolve_ext_calls(&mut module)?;
    // Second pass: resolve impl/trait-bound calls in functions generated by resolve_ext_calls.
    implement_blocks::resolve_impl_calls(&mut module, registry)?;
    // Resolve template-named function calls: creates concrete function copies from
    // generic templates by walking the AST for FunctionCall nodes with type_params.
    resolve_all_template_function_calls(&mut module, registry)?;
    // Discover generic class instances from function bodies (ClassNew/RecordCreate/EnumCreate
    // nodes with type_params) and create concrete TypeDefs + method functions.
    let instances = discover_generic_class_instances(&module);
    instantiate_generic_classes(&mut module, registry, &instances);
    // Third pass: resolve impl/ext calls in functions created by template function/class instantiation.
    // These concrete functions may contain InterfaceObjectCoerce, ImplFunctionCall, etc.
    implement_blocks::resolve_impl_calls(&mut module, registry)?;
    extension_blocks::resolve_ext_calls(&mut module)?;
    // Resolve template-named function calls that were introduced by instantiate_generic_classes
    // (class method bodies may contain template-named calls from generic inference).
    resolve_all_template_function_calls(&mut module, registry)?;
    // Second round: the 3rd resolve_impl_calls may have created functions referencing new
    // generic classes (e.g., ArrayIterator<Char> from Iterable<Char>.Array<Char>.iterator).
    // Discover and instantiate those class methods.
    let instances = discover_generic_class_instances(&module);
    instantiate_generic_classes(&mut module, registry, &instances);
    // Resolve template calls in newly created class method bodies
    resolve_all_template_function_calls(&mut module, registry)?;
    // Fourth pass: resolve impl/ext calls in functions created by the latest template/class
    // instantiation rounds.
    implement_blocks::resolve_impl_calls(&mut module, registry)?;
    extension_blocks::resolve_ext_calls(&mut module)?;
    // Ensure all concrete ClassTypeDefs have their vtable method functions created.
    // This handles classes from dependency packages whose vtable references template-derived
    // function names but the concrete functions weren't created in this project's monomorphize.
    ensure_class_method_functions(&mut module, registry);
    // The newly created functions may reference new generic class types (e.g., iterators).
    // Run discovery + instantiation to create those TypeDefs and their methods.
    let instances = discover_generic_class_instances(&module);
    instantiate_generic_classes(&mut module, registry, &instances);
    resolve_all_template_function_calls(&mut module, registry)?;
    implement_blocks::resolve_impl_calls(&mut module, registry)?;
    extension_blocks::resolve_ext_calls(&mut module)?;
    ensure_class_method_functions(&mut module, registry);
    settle_specializations(&mut module, registry)?;
    module.function_templates.extend(
        module
            .functions
            .iter()
            .filter(|(_, function)| !function.type_params.is_empty())
            .map(|(name, function)| (name.clone(), function.clone())),
    );

    // Strip generic function templates — codegen only emits monomorphized instances; template
    // bodies still carry `TypeParameter` types. Generic Record/Enum/Class TypeDefs remain — they
    // are the canonical erased entries, one per generic definition. Globals on generic
    // classes/modules are stored as single canonical entries (no templates).
    //
    // Note: there is no longer a type-collection walk here. Arrays are predeclared as a fixed set
    // in codegen (`emit_array_types`); interface objects are registered at their coercion sites by
    // `coerce::elaborate_coercions`. Monomorphize now only monomorphizes *functions*.
    module.functions.retain(|_, f| f.type_params.is_empty());

    // PHASE 1 INVARIANT: every user-declared Record/Enum/Class TypeDef must be keyed by its
    // erased mangled name (MangledName::for_type(fqn)). Tuples are exempt — they are synthetic
    // records with an empty package and use $Tuple$T1$T2 mangling per shape (not erased).
    #[cfg(debug_assertions)]
    for (key, td) in &module.types {
        match td {
            TypeDef::Record(r) if !r.fqn.package.0.is_empty() => {
                let expected = MangledName::for_type(&r.fqn);
                assert_eq!(
                    key, &expected,
                    "Record TypeDef keyed by {:?}, expected erased {:?}",
                    key, expected
                );
                assert_eq!(
                    &r.mangled_name, &expected,
                    "Record mangled_name mismatch for {:?}",
                    r.fqn
                );
            }
            TypeDef::Enum(e) => {
                let expected = MangledName::for_type(&e.fqn);
                assert_eq!(
                    key, &expected,
                    "Enum TypeDef keyed by {:?}, expected erased {:?}",
                    key, expected
                );
                assert_eq!(
                    &e.mangled_name, &expected,
                    "Enum mangled_name mismatch for {:?}",
                    e.fqn
                );
            }
            TypeDef::Class(c) => {
                let expected = MangledName::for_type(&c.fqn);
                assert_eq!(
                    key, &expected,
                    "Class TypeDef keyed by {:?}, expected erased {:?}",
                    key, expected
                );
                assert_eq!(
                    &c.mangled_name, &expected,
                    "Class mangled_name mismatch for {:?}",
                    c.fqn
                );
            }
            _ => {}
        }
    }

    if let Some(message) = normalization.errors().into_iter().next()
        && let Some(function) = module.functions.values().next()
    {
        return Err(SpecializationError {
            span: function.span.clone(),
            message,
        });
    }
    Ok(module)
}

/// Implementations and generic helpers can introduce one another recursively.
fn settle_specializations(
    module: &mut TypedModule,
    registry: &Registry,
) -> Result<(), SpecializationError> {
    let mut rounds = SpecializationRounds::default();
    loop {
        let previous_names: BTreeSet<_> = module.functions.keys().cloned().collect();
        implement_blocks::resolve_impl_calls(module, registry)?;
        extension_blocks::resolve_ext_calls(module)?;
        resolve_all_template_function_calls(module, registry)?;
        let instances = discover_generic_class_instances(module);
        instantiate_generic_classes(module, registry, &instances);
        ensure_class_method_functions(module, registry);
        if module.functions.len() == previous_names.len() {
            return Ok(());
        }
        rounds.advance_for_new_functions(module, &previous_names)?;
    }
}

/// Re-collect templates and resolve template-named calls in all function bodies.
/// Called after instantiate_generic_classes to handle template calls in class method bodies.
fn resolve_all_template_function_calls(
    module: &mut TypedModule,
    registry: &Registry,
) -> Result<(), SpecializationError> {
    let templates: BTreeMap<MangledName, TypedFunction> = module
        .functions
        .iter()
        .chain(module.function_templates.iter())
        .filter(|(_, f)| !f.type_params.is_empty())
        .map(|(name, f)| (name.clone(), f.clone()))
        .collect();
    if templates.is_empty() {
        return Ok(());
    }
    let ancestry = collect_class_ancestry(module, registry);
    resolve_template_function_calls(module, &templates, &ancestry)
}

/// What a class declares about the class it extends: its own type parameters, and
/// the parent type WITH the type arguments the `extends` clause supplied.
///
/// Owned and built up front rather than read from `module.types` on demand: the
/// rewrite walks hold `&mut` on the very map this would be read from.
struct ClassAncestor {
    type_params: Vec<TypeParamName>,
    parent_type: Option<Type>,
}

/// Keyed by the class's erased mangled name — the same key `Type::Class` and
/// `Type::GenericClass` carry, so a type can be looked up without an FQN detour.
type ClassAncestry = BTreeMap<MangledName, ClassAncestor>;

fn collect_class_ancestry(module: &TypedModule, registry: &Registry) -> ClassAncestry {
    module
        .types
        .iter()
        .filter_map(|(mn, td)| match td {
            TypeDef::Class(cls) => {
                // A GENERIC class's typed-AST template carries `parent_type: None` —
                // it is the canonical erased entry and its parent instantiation was
                // left "resolved during monomorphize", which nothing does since
                // per-instantiation ClassTypeDefs went away. The registry kept it:
                // `parent_type_expr` is the parent type with this class's own type
                // parameters still in it (`Box<A>` for `Middle<A> extends Box<A>`),
                // which is exactly what climbing needs to substitute into.
                let parent_type = cls.parent_type.clone().or_else(|| {
                    registry
                        .get_class_type(&cls.fqn)
                        .and_then(|sig| sig.parent_type_expr.clone())
                });
                Some((
                    mn.clone(),
                    ClassAncestor {
                        type_params: cls.type_params.clone(),
                        parent_type,
                    },
                ))
            }
            _ => None,
        })
        .collect()
}

/// Re-express `ty` as the instantiation of `target` that it inherits, or `None` if
/// `target` is not one of its ancestors.
///
/// This is what makes an inherited method callable through a receiver typed as the
/// SUBCLASS. Every generic template is instantiated by unifying its parameter types
/// against the concrete argument types at the call, and `Box<T>` does not unify with
/// `IntBox` — so a call to a `final` method of a generic base class through a
/// subclass-typed receiver derived no type arguments, kept the template name, and
/// reached codegen as `missing function index for: Box.pair$Box<T>$Int32`. Typing
/// the same receiver as `Box<Int32>` worked, which is why nothing in the standard
/// library ever tripped over it.
///
/// Each step substitutes the current instantiation's arguments into the parent type
/// the `extends` clause declared, so `Foo<Int32> extends Bar<T>` climbs to
/// `Bar<Int32>` rather than to `Bar<T>`.
fn upcast_to_ancestor(ty: &Type, target: &MangledName, ancestry: &ClassAncestry) -> Option<Type> {
    let mut current = ty.clone();
    // Bounded: the hierarchy is a DAG by construction (the typechecker rejects
    // cycles), and a bound costs nothing next to a compiler that hangs if it is
    // ever wrong.
    for _ in 0..64 {
        let (mangled, type_params): (MangledName, Vec<Type>) = match &current {
            Type::Class(_, mn) => (mn.clone(), vec![]),
            Type::GenericClass {
                mangled_name,
                type_args,
                ..
            } => (
                mangled_name.clone(),
                type_args.iter().map(|(_, t)| t.clone()).collect(),
            ),
            _ => return None,
        };
        if &mangled == target {
            return Some(current);
        }
        let ancestor = ancestry.get(&mangled)?;
        let parent = ancestor.parent_type.clone()?;
        let sub: BTreeMap<TypeParamName, Type> = ancestor
            .type_params
            .iter()
            .cloned()
            .zip(type_params)
            .collect();
        current = if sub.is_empty() {
            parent
        } else {
            substitute::apply_type_substitution(&parent, &sub)
        };
    }
    None
}

/// Unify one template parameter type against a concrete argument type, upcasting the
/// argument to the ancestor the parameter names when the parameter is a generic class
/// the argument merely inherits from.
fn unify_param_type(
    param_ty: &Type,
    concrete_ty: &Type,
    ancestry: &ClassAncestry,
    bindings: &mut BTreeMap<TypeParamName, Type>,
) {
    if let Type::GenericClass { mangled_name, .. } = param_ty
        && !matches!(concrete_ty, Type::GenericClass { mangled_name: m, .. } if m == mangled_name)
        && let Some(upcast) = upcast_to_ancestor(concrete_ty, mangled_name, ancestry)
    {
        substitute::unify_type(param_ty, &upcast, bindings);
        return;
    }
    substitute::unify_type(param_ty, concrete_ty, bindings);
}

/// Resolve FunctionCall/FunctionRef nodes that reference template names.
/// For each such call with concrete type_args, compute concrete name =
/// template_name.with_type_args(type_args), create the concrete function, and
/// rewrite the call to use the concrete name. Runs as a fixpoint loop.
fn resolve_template_function_calls(
    module: &mut TypedModule,
    templates: &BTreeMap<MangledName, TypedFunction>,
    ancestry: &ClassAncestry,
) -> Result<(), SpecializationError> {
    let mut rounds = SpecializationRounds::default();
    loop {
        let mut new_functions: BTreeMap<MangledName, TypedFunction> = BTreeMap::new();

        // Scan all function bodies for template-named calls and create concrete copies
        for func in module.functions.values() {
            collect_template_calls(
                &func.body,
                templates,
                ancestry,
                &module.functions,
                &mut new_functions,
            );
        }
        for global in module.globals.values() {
            collect_template_calls(
                &global.initializer,
                templates,
                ancestry,
                &module.functions,
                &mut new_functions,
            );
        }
        for test in &module.tests {
            collect_template_calls(
                &test.body,
                templates,
                ancestry,
                &module.functions,
                &mut new_functions,
            );
        }
        // Scan class initializers and extends_args
        for type_def in module.types.values() {
            if let TypeDef::Class(cls) = type_def {
                for stmt in &cls.initializer {
                    collect_template_calls(
                        stmt,
                        templates,
                        ancestry,
                        &module.functions,
                        &mut new_functions,
                    );
                }
                if let Some(ref extends_args) = cls.extends_args {
                    for arg in extends_args {
                        collect_template_calls(
                            arg,
                            templates,
                            ancestry,
                            &module.functions,
                            &mut new_functions,
                        );
                    }
                }
            }
        }

        // Rewrite FunctionCall/FunctionRef names: template_name → concrete_name
        // Always rewrite even if no new functions were created, because existing concrete
        // functions may still contain template-named calls that need rewriting.
        for func in module.functions.values_mut() {
            rewrite_template_calls_in_place(&mut func.body, templates, ancestry);
        }
        for global in module.globals.values_mut() {
            rewrite_template_calls_in_place(&mut global.initializer, templates, ancestry);
        }
        for test in &mut module.tests {
            rewrite_template_calls_in_place(&mut test.body, templates, ancestry);
        }
        // Rewrite class initializers and extends_args
        for type_def in module.types.values_mut() {
            if let TypeDef::Class(cls) = type_def {
                for stmt in &mut cls.initializer {
                    rewrite_template_calls_in_place(stmt, templates, ancestry);
                }
                if let Some(ref mut extends_args) = cls.extends_args {
                    for arg in extends_args {
                        rewrite_template_calls_in_place(arg, templates, ancestry);
                    }
                }
            }
        }

        let Some(function) = new_functions.values().next() else {
            return Ok(());
        };
        rounds.advance(function)?;
        module.functions.extend(new_functions);
    }
}

/// Collect FunctionCall/FunctionRef where name is a template and type_args are concrete.
/// Also handles intra-module calls where type_args is empty: derives type_args by
/// unifying template param types with the call's concrete arg types.
fn collect_template_calls(
    expr: &TypedExpr,
    templates: &BTreeMap<MangledName, TypedFunction>,
    ancestry: &ClassAncestry,
    existing: &BTreeMap<MangledName, TypedFunction>,
    new_functions: &mut BTreeMap<MangledName, TypedFunction>,
) {
    use crate::common::types::TypeParamName;
    match &expr.kind {
        TypedExprKind::FunctionCall {
            name,
            type_params,
            args,
        } => {
            if let Some(template) = templates.get(name) {
                let derived_type_args = if !type_params.is_empty() {
                    // Explicit type_params from generic call resolution
                    if type_params.iter().any(|t| t.contains_type_parameter()) {
                        None
                    } else if template.type_params.len() == type_params.len() {
                        Some(type_params.clone())
                    } else {
                        None
                    }
                } else {
                    // Intra-module call: derive type_args from concrete arg types
                    derive_type_args_from_call(template, args, ancestry)
                };
                if let Some(type_args) = derived_type_args {
                    let concrete_name = name.clone().with_type_args(&type_args);
                    if !existing.contains_key(&concrete_name)
                        && !new_functions.contains_key(&concrete_name)
                    {
                        let sub: BTreeMap<TypeParamName, Type> = template
                            .type_params
                            .iter()
                            .zip(type_args.iter())
                            .map(|(tp, t)| (tp.clone(), t.clone()))
                            .collect();
                        let concrete = substitute::substitute_types_in_function(
                            template,
                            &sub,
                            concrete_name.clone(),
                        );
                        new_functions.insert(concrete_name, concrete);
                    }
                }
            }
        }
        TypedExprKind::FunctionRef { name, type_params } => {
            if let Some(template) = templates.get(name) {
                let derived_type_args = if !type_params.is_empty() {
                    if type_params.iter().any(|t| t.contains_type_parameter()) {
                        None
                    } else if template.type_params.len() == type_params.len() {
                        Some(type_params.clone())
                    } else {
                        None
                    }
                } else {
                    // Derive from expression type (Function type)
                    derive_type_args_from_function_ref(template, &expr.ty, ancestry)
                };
                if let Some(type_args) = derived_type_args {
                    let concrete_name = name.clone().with_type_args(&type_args);
                    if !existing.contains_key(&concrete_name)
                        && !new_functions.contains_key(&concrete_name)
                    {
                        let sub: BTreeMap<TypeParamName, Type> = template
                            .type_params
                            .iter()
                            .zip(type_args.iter())
                            .map(|(tp, t)| (tp.clone(), t.clone()))
                            .collect();
                        let concrete = substitute::substitute_types_in_function(
                            template,
                            &sub,
                            concrete_name.clone(),
                        );
                        new_functions.insert(concrete_name, concrete);
                    }
                }
            }
        }
        _ => {}
    }
    visit_expr_children(expr, |child| {
        collect_template_calls(child, templates, ancestry, existing, new_functions);
    });
}

/// Derive type_args for an intra-module template call by unifying template param types
/// with the concrete arg types at the call site.
fn derive_type_args_from_call(
    template: &TypedFunction,
    args: &[TypedExpr],
    ancestry: &ClassAncestry,
) -> Option<Vec<Type>> {
    let mut bindings: BTreeMap<TypeParamName, Type> = BTreeMap::new();
    for (param, arg) in template.params.iter().zip(args.iter()) {
        unify_param_type(&param.ty, &arg.ty, ancestry, &mut bindings);
    }
    let derived: Vec<Type> = template
        .type_params
        .iter()
        .filter_map(|tp| bindings.get(tp).cloned())
        .collect();
    if derived.len() == template.type_params.len()
        && !derived.iter().any(|t| t.contains_type_parameter())
    {
        Some(derived)
    } else {
        None
    }
}

/// Derive type_args for a FunctionRef by unifying template param/return types
/// with the concrete expression type (a Function type).
fn derive_type_args_from_function_ref(
    template: &TypedFunction,
    expr_ty: &Type,
    ancestry: &ClassAncestry,
) -> Option<Vec<Type>> {
    let mut bindings: BTreeMap<TypeParamName, Type> = BTreeMap::new();
    if let Type::Function(concrete_params, concrete_ret) = expr_ty {
        for (param, concrete_param_ty) in template.params.iter().zip(concrete_params.iter()) {
            unify_param_type(&param.ty, concrete_param_ty, ancestry, &mut bindings);
        }
        substitute::unify_type(&template.return_type, concrete_ret, &mut bindings);
    }
    let derived: Vec<Type> = template
        .type_params
        .iter()
        .filter_map(|tp| bindings.get(tp).cloned())
        .collect();
    if derived.len() == template.type_params.len()
        && !derived.iter().any(|t| t.contains_type_parameter())
    {
        Some(derived)
    } else {
        None
    }
}

/// In-place rewrite: if FunctionCall/FunctionRef name is a template, replace name with
/// the concrete name (template_name.with_type_args). Handles both explicit type_args
/// and intra-module calls with empty type_args (derived from arg types).
fn rewrite_template_calls_in_place(
    expr: &mut TypedExpr,
    templates: &BTreeMap<MangledName, TypedFunction>,
    ancestry: &ClassAncestry,
) {
    // Clone expr.ty before mutable match for FunctionRef derivation
    let expr_ty = expr.ty.clone();
    match &mut expr.kind {
        TypedExprKind::FunctionCall {
            name,
            type_params,
            args,
        } => {
            if let Some(template) = templates.get(&*name) {
                if !type_params.is_empty()
                    && !type_params.iter().any(|t| t.contains_type_parameter())
                {
                    *name = name.clone().with_type_args(type_params);
                    *type_params = vec![];
                } else if type_params.is_empty() {
                    // Intra-module call: derive type_args from concrete arg types
                    if let Some(derived) = derive_type_args_from_call(template, args, ancestry) {
                        *name = name.clone().with_type_args(&derived);
                    }
                }
            }
        }
        TypedExprKind::FunctionRef { name, type_params } => {
            if let Some(template) = templates.get(&*name) {
                if !type_params.is_empty()
                    && !type_params.iter().any(|t| t.contains_type_parameter())
                {
                    *name = name.clone().with_type_args(type_params);
                    *type_params = vec![];
                } else if type_params.is_empty()
                    && let Some(derived) =
                        derive_type_args_from_function_ref(template, &expr_ty, ancestry)
                {
                    *name = name.clone().with_type_args(&derived);
                }
            }
        }
        _ => {}
    }
    // Recurse into children
    visit_expr_children_mut(expr, |child| {
        rewrite_template_calls_in_place(child, templates, ancestry);
    });
}

/// Instantiate concrete ClassTypeDefs and method functions from generic class templates.
/// Uses discovered class instances from AST walking.
/// Creates concrete ClassTypeDef (with substituted fields, initializer, etc.) and
/// concrete method functions from template method TypedFunctions.
fn instantiate_generic_classes(
    module: &mut TypedModule,
    registry: &Registry,
    instances: &BTreeMap<MangledName, (Fqn, Vec<Type>)>,
) {
    use crate::typechecker::types::{ClassTypeDef, TypeDef};

    if instances.is_empty() {
        return;
    }

    // Collect template ClassTypeDefs (those with non-empty type_params in module.types)
    let class_templates: BTreeMap<MangledName, ClassTypeDef> = module
        .types
        .iter()
        .filter_map(|(name, td)| {
            if let TypeDef::Class(cls) = td
                && !cls.type_params.is_empty()
            {
                return Some((name.clone(), cls.clone()));
            }
            None
        })
        .collect();

    // Collect template functions (those with non-empty type_params)
    let func_templates: BTreeMap<MangledName, TypedFunction> = module
        .functions
        .iter()
        .filter(|(_, f)| !f.type_params.is_empty())
        .map(|(name, f)| (name.clone(), f.clone()))
        .collect();

    let mut new_functions: BTreeMap<MangledName, TypedFunction> = BTreeMap::new();

    // Process instances, instantiating parent classes first when needed.
    // Use a work queue to handle transitive parent instantiation.
    let mut work: Vec<(MangledName, Fqn, Vec<Type>)> = instances
        .iter()
        .map(|(mn, (fqn, ta))| (mn.clone(), fqn.clone(), ta.clone()))
        .collect();
    let mut processed: std::collections::BTreeSet<MangledName> = std::collections::BTreeSet::new();

    while let Some((concrete_mn, class_fqn, type_args)) = work.pop() {
        if processed.contains(&concrete_mn) {
            continue;
        }
        // Skip entries with unresolved TypeParameter types
        if type_args.iter().any(|t| t.contains_type_parameter()) {
            continue;
        }
        processed.insert(concrete_mn.clone());

        let template_mn = MangledName::for_type(&class_fqn);
        let template = match class_templates.get(&template_mn) {
            Some(t) => t,
            None => continue,
        };

        // Always create concrete method functions from templates.
        let sub: BTreeMap<TypeParamName, Type> = template
            .type_params
            .iter()
            .zip(type_args.iter())
            .map(|(tp, t)| (tp.clone(), t.clone()))
            .collect();
        create_concrete_class_methods(
            registry,
            template,
            &func_templates,
            &sub,
            &module.functions,
            &mut new_functions,
        );

        // No per-instantiation ClassTypeDef is created — under full erasure, the canonical
        // ClassTypeDef from collect (keyed by MangledName::for_type(fqn)) is shared by every
        // instantiation. Only the methods are monomorphized.
    }

    module.functions.extend(new_functions);

    // Fix up non-generic ClassTypeDefs whose parent was just created.
    // During inference, non-generic classes extending generic parents couldn't copy
    // parent fields because the parent ClassTypeDef didn't exist yet.
    fixup_class_parent_fields(module);
}

/// Fix up ClassTypeDefs whose parent fields are missing because the parent
/// ClassTypeDef was created by monomorphize after the child was inferred,
/// or because the canonical (erased) generic class never had its parent's fields
/// prepended (Phase 1 removed the per-instantiation prepending pass).
fn fixup_class_parent_fields(module: &mut TypedModule) {
    // Collect classes that need fixup: have a parent but no parent fields.
    // Apply to BOTH non-generic and canonical generic classes — the WASM subtype rule
    // requires the child's struct to be a prefix-superset of the parent's struct.
    let needs_fixup: Vec<(MangledName, MangledName)> = module
        .types
        .iter()
        .filter_map(|(mn, td)| {
            if let TypeDef::Class(cls) = td {
                {
                    if let Some(ref parent_mn) = cls.parent_mangled_name {
                        // Check if parent exists and child is missing parent fields
                        if let Some(TypeDef::Class(parent_cls)) = module.types.get(parent_mn)
                            && !parent_cls.fields.is_empty()
                            && !cls.fields.iter().any(|f| {
                                parent_cls
                                    .fields
                                    .iter()
                                    .any(|pf| pf.name == f.name && pf.declared_by == f.declared_by)
                            })
                        {
                            return Some((mn.clone(), parent_mn.clone()));
                        }
                    }
                }
            }
            None
        })
        .collect();

    for (child_mn, parent_mn) in needs_fixup {
        let parent_fields: Vec<crate::typechecker::types::ClassFieldDef>;
        let parent_hierarchy_root: MangledName;
        let parent_type_params: Vec<TypeParamName>;
        if let Some(TypeDef::Class(parent_cls)) = module.types.get(&parent_mn) {
            parent_fields = parent_cls.fields.clone();
            parent_hierarchy_root = parent_cls.hierarchy_root_mangled.clone();
            parent_type_params = parent_cls.type_params.clone();
        } else {
            continue;
        }
        // Build substitution from the child's `parent_type` (which carries the concrete
        // type args used at the `extends` clause) so we substitute the parent's
        // TypeVariable field types with the concrete types the child specialized at.
        let parent_subst: BTreeMap<TypeParamName, Type> = {
            let child_parent_type = if let Some(TypeDef::Class(cls)) = module.types.get(&child_mn) {
                cls.parent_type.clone()
            } else {
                None
            };
            match child_parent_type {
                Some(Type::GenericClass { type_args, .. }) => parent_type_params
                    .iter()
                    .zip(type_args.iter())
                    .map(|(tp, (_, ty))| (tp.clone(), ty.clone()))
                    .collect(),
                _ => BTreeMap::new(),
            }
        };
        let substituted_parent_fields: Vec<crate::typechecker::types::ClassFieldDef> =
            parent_fields
                .into_iter()
                .map(|f| crate::typechecker::types::ClassFieldDef {
                    ty: if parent_subst.is_empty() {
                        f.ty
                    } else {
                        substitute::apply_type_substitution(&f.ty, &parent_subst)
                    },
                    ..f
                })
                .collect();
        if let Some(TypeDef::Class(cls)) = module.types.get_mut(&child_mn) {
            // Prepend parent fields (with type-args substituted)
            let own_fields = std::mem::take(&mut cls.fields);
            cls.fields = substituted_parent_fields;
            cls.fields.extend(own_fields);
            // Update hierarchy root
            cls.hierarchy_root_mangled = parent_hierarchy_root;
            // Inference already computed the complete inherited vtable from the
            // registry. Field repair must preserve those slot indices and the
            // ancestor arguments expressed in the child's parameter space.
        }
    }
}

/// Ensure all concrete ClassTypeDefs have their vtable and non-vtable method functions.
/// When a concrete ClassTypeDef is created in a dependency package and merged into the current
/// module, its vtable references function names (e.g., `Foo.bar$Foo<T>$T#Int32`) that may not
/// exist yet in the current module's functions. This function scans all concrete ClassTypeDefs,
/// finds missing method functions, and creates them from templates.
fn ensure_class_method_functions(module: &mut TypedModule, registry: &Registry) {
    let func_templates: BTreeMap<MangledName, TypedFunction> = module
        .functions
        .iter()
        .filter(|(_, f)| !f.type_params.is_empty())
        .map(|(name, f)| (name.clone(), f.clone()))
        .collect();
    if func_templates.is_empty() {
        return;
    }

    let class_templates: BTreeMap<MangledName, crate::typechecker::types::ClassTypeDef> = module
        .types
        .iter()
        .filter_map(|(name, td)| {
            if let TypeDef::Class(cls) = td
                && !cls.type_params.is_empty()
            {
                return Some((name.clone(), cls.clone()));
            }
            None
        })
        .collect();

    let mut new_functions: BTreeMap<MangledName, TypedFunction> = BTreeMap::new();

    // Scan all concrete ClassTypeDefs for missing vtable/method functions
    for td in module.types.values() {
        let cls = match td {
            TypeDef::Class(cls) if cls.type_params.is_empty() => cls,
            _ => continue,
        };
        // Methods inherited from a GENERIC ancestor onto this class (e.g. a
        // non-generic class extending `AsyncInputStream<TlsIoError>` inheriting a
        // default virtual method). The slot's `impl_type_params` carry the ancestor
        // binding; monomorphize the ancestor's template method at those args so
        // the concrete function codegen looks up exists. Own methods and
        // straight-through inheritance leave `impl_type_params` in terms of the
        // class's own params (empty here for a non-generic class), so they are
        // handled by the template-based path below and skipped here.
        for slot in &cls.vtable_methods {
            if slot.impl_type_params.is_empty()
                || slot
                    .impl_type_params
                    .iter()
                    .any(|t| t.contains_type_parameter())
            {
                continue;
            }
            let template_method_mn = MangledName::for_function(&slot.impl_fqn, &slot.param_types);
            let tmpl_func = match func_templates.get(&template_method_mn) {
                Some(f) => f,
                None => continue,
            };
            let concrete_mn = template_method_mn
                .clone()
                .with_type_args(&slot.impl_type_params);
            if module.functions.contains_key(&concrete_mn)
                || new_functions.contains_key(&concrete_mn)
            {
                continue;
            }
            let sub: BTreeMap<TypeParamName, Type> = tmpl_func
                .type_params
                .iter()
                .cloned()
                .zip(slot.impl_type_params.iter().cloned())
                .collect();
            let concrete = class_method_bounds::specialize_vtable_method(
                registry,
                slot,
                tmpl_func,
                &sub,
                concrete_mn.clone(),
            );
            new_functions.insert(concrete_mn, concrete);
        }
        // Check if any vtable method is missing. The slot's concrete mangled name is
        // `for_function(impl_fqn, param_types)` — the same recipe used at declaration time.
        let needs_methods = cls.vtable_methods.iter().any(|slot| {
            let mn = MangledName::for_function(&slot.impl_fqn, &slot.param_types);
            !module.functions.contains_key(&mn) && !new_functions.contains_key(&mn)
        });
        if !needs_methods {
            continue;
        }
        // Find the template ClassTypeDef
        let template_mn = MangledName::for_type(&cls.fqn);
        let template = match class_templates.get(&template_mn) {
            Some(t) => t,
            None => continue,
        };
        // Derive type_args from mangled name by matching template type params
        // against the concrete class. We extract them from the concrete class's
        // constructor param types or vtable method names.
        // Simplest approach: parse type_args from the mangled name suffix.
        let base_name = template_mn.0.as_str();
        let concrete_name = cls.mangled_name.0.as_str();
        if !concrete_name.starts_with(base_name) || concrete_name.len() <= base_name.len() {
            continue;
        }
        // Extract type args by matching template constructor params against concrete ones
        if template.type_params.is_empty()
            || template.constructor_params.len() != cls.constructor_params.len()
        {
            continue;
        }
        // Build substitution by unifying template param types with concrete param types
        let mut sub: BTreeMap<TypeParamName, Type> = BTreeMap::new();
        for (tmpl_param, conc_param) in template
            .constructor_params
            .iter()
            .zip(cls.constructor_params.iter())
        {
            extract_type_param_mapping(&tmpl_param.ty, &conc_param.ty, &mut sub);
        }
        // Also try from fields
        for (tmpl_field, conc_field) in template.fields.iter().zip(cls.fields.iter()) {
            extract_type_param_mapping(&tmpl_field.ty, &conc_field.ty, &mut sub);
        }
        if sub.len() != template.type_params.len() {
            continue;
        }
        let type_args: Vec<Type> = template
            .type_params
            .iter()
            .filter_map(|tp| sub.get(tp).cloned())
            .collect();
        if type_args.len() != template.type_params.len() {
            continue;
        }
        create_concrete_class_methods(
            registry,
            template,
            &func_templates,
            &sub,
            &module.functions,
            &mut new_functions,
        );
    }

    module.functions.extend(new_functions);
}

/// Extract type parameter → concrete type mappings by unifying a template type with a concrete type.
fn extract_type_param_mapping(
    template_ty: &Type,
    concrete_ty: &Type,
    sub: &mut BTreeMap<TypeParamName, Type>,
) {
    match (template_ty, concrete_ty) {
        (Type::TypeVariable(name, _) | Type::GenericParam(name, _, _), _)
            if !concrete_ty.contains_type_parameter() =>
        {
            sub.entry(TypeParamName(name.to_string()))
                .or_insert_with(|| concrete_ty.clone());
        }
        (Type::Array(t_elem), Type::Array(c_elem)) => {
            extract_type_param_mapping(t_elem, c_elem, sub);
        }
        (
            Type::GenericClass {
                type_args: t_args, ..
            },
            Type::GenericClass {
                type_args: c_args, ..
            },
        )
        | (
            Type::GenericRecord {
                type_args: t_args, ..
            },
            Type::GenericRecord {
                type_args: c_args, ..
            },
        )
        | (
            Type::GenericEnum {
                type_args: t_args, ..
            },
            Type::GenericEnum {
                type_args: c_args, ..
            },
        ) => {
            for ((_, t), (_, c)) in t_args.iter().zip(c_args.iter()) {
                extract_type_param_mapping(t, c, sub);
            }
        }
        (Type::Function(t_params, t_ret), Type::Function(c_params, c_ret)) => {
            for (t, c) in t_params.iter().zip(c_params.iter()) {
                extract_type_param_mapping(t, c, sub);
            }
            extract_type_param_mapping(t_ret, c_ret, sub);
        }
        _ => {}
    }
}

/// Create concrete vtable method functions for a generic class instance.
fn create_concrete_class_methods(
    registry: &Registry,
    template: &crate::typechecker::types::ClassTypeDef,
    func_templates: &BTreeMap<MangledName, TypedFunction>,
    sub: &BTreeMap<TypeParamName, Type>,
    existing_functions: &BTreeMap<MangledName, TypedFunction>,
    new_functions: &mut BTreeMap<MangledName, TypedFunction>,
) {
    // Create concrete method functions from templates (vtable methods). Each slot's
    // template mangled name = for_function(impl_fqn, param_types) — same as at declaration.
    for slot in &template.vtable_methods {
        let template_method_mn = MangledName::for_function(&slot.impl_fqn, &slot.param_types);
        if let Some(tmpl_func) = func_templates.get(&template_method_mn) {
            // Inherited slots express the ancestor's arguments in the child's
            // parameter space. Specialize the ancestor using that binding,
            // rather than assuming its parameter names and order match ours.
            let implementation_args: Vec<_> = slot
                .impl_type_params
                .iter()
                .map(|argument| substitute::apply_type_substitution(argument, sub))
                .collect();
            let implementation_sub = tmpl_func
                .type_params
                .iter()
                .cloned()
                .zip(implementation_args.iter().cloned())
                .collect();
            let concrete_method_mn = template_method_mn
                .clone()
                .with_type_args(&implementation_args);

            if !existing_functions.contains_key(&concrete_method_mn)
                && !new_functions.contains_key(&concrete_method_mn)
            {
                let concrete = class_method_bounds::specialize_vtable_method(
                    registry,
                    slot,
                    tmpl_func,
                    &implementation_sub,
                    concrete_method_mn.clone(),
                );
                new_functions.insert(concrete_method_mn, concrete);
            }
        }
    }
}

/// Discover generic class instances from function bodies.
/// After resolve_impl_calls creates concrete functions via substitution, those may contain
/// ClassNew nodes for generic classes
/// (because they were only referenced inside template bodies during inference).
fn discover_generic_class_instances(
    module: &TypedModule,
) -> BTreeMap<MangledName, (Fqn, Vec<Type>)> {
    let mut discovered: BTreeMap<MangledName, (Fqn, Vec<Type>)> = BTreeMap::new();

    fn collect_from_expr(
        expr: &TypedExpr,
        discovered: &mut BTreeMap<MangledName, (Fqn, Vec<Type>)>,
    ) {
        // Check if the expression type is a GenericClass
        if let Type::GenericClass { fqn, type_args, .. } = &expr.ty
            && !type_args.iter().any(|(_, t)| t.contains_type_parameter())
        {
            let plain_args: Vec<Type> = type_args.iter().map(|(_, t)| t.clone()).collect();
            // Synthetic per-instantiation key — types share an erased mangled name,
            // but methods are still monomorphized per type-arg combination.
            let key = MangledName::for_function(fqn, &plain_args);
            discovered
                .entry(key)
                .or_insert_with(|| (fqn.clone(), plain_args));
        }
        // Recurse into sub-expressions
        match &expr.kind {
            TypedExprKind::Block(exprs) => {
                exprs.iter().for_each(|e| collect_from_expr(e, discovered))
            }
            TypedExprKind::FunctionCall { args, .. }
            | TypedExprKind::IntrinsicCall { args, .. }
            | TypedExprKind::ClassNew { args, .. }
            | TypedExprKind::ClassSuperCall { args, .. }
            | TypedExprKind::ClassStructCreate { fields: args, .. }
            | TypedExprKind::EnumCreate { args, .. }
            | TypedExprKind::EnumVariantRecordCreate { args, .. }
            | TypedExprKind::ArrayLiteral { elements: args }
            | TypedExprKind::ClosureCall { args, .. }
            | TypedExprKind::ClassVirtualCall { args, .. }
            | TypedExprKind::InterfaceObjectMethodCall { args, .. } => {
                args.iter().for_each(|a| collect_from_expr(a, discovered));
                // Also handle receiver/callee/object in these variants
                match &expr.kind {
                    TypedExprKind::ClosureCall { callee, .. } => {
                        collect_from_expr(callee, discovered)
                    }
                    TypedExprKind::ClassVirtualCall { object, .. } => {
                        collect_from_expr(object, discovered)
                    }
                    TypedExprKind::InterfaceObjectMethodCall { receiver, .. } => {
                        collect_from_expr(receiver, discovered)
                    }
                    _ => {}
                }
            }
            TypedExprKind::If {
                condition,
                then_branch,
                else_branch,
            } => {
                collect_from_expr(condition, discovered);
                collect_from_expr(then_branch, discovered);
                if let Some(e) = else_branch {
                    collect_from_expr(e, discovered);
                }
            }
            TypedExprKind::While { condition, body } => {
                collect_from_expr(condition, discovered);
                collect_from_expr(body, discovered);
            }
            TypedExprKind::Let { value, .. }
            | TypedExprKind::Assign { value, .. }
            | TypedExprKind::NewtypeCreate { value, .. }
            | TypedExprKind::NewtypeValue { value, .. }
            | TypedExprKind::TypeCast { value, .. }
            | TypedExprKind::TypeTest { value, .. }
            | TypedExprKind::BoxToAny { inner: value }
            | TypedExprKind::NamedCall { call: value, .. }
            | TypedExprKind::Panic { message: value }
            | TypedExprKind::Return { value, .. }
            | TypedExprKind::GlobalAssign { value, .. }
            | TypedExprKind::UnaryOp { operand: value, .. } => collect_from_expr(value, discovered),
            TypedExprKind::BinaryOp { left, right, .. } => {
                collect_from_expr(left, discovered);
                collect_from_expr(right, discovered);
            }
            TypedExprKind::FieldAccess { object, .. } | TypedExprKind::MethodRef { object, .. } => {
                collect_from_expr(object, discovered);
            }
            TypedExprKind::FieldAssign { object, value, .. } => {
                collect_from_expr(object, discovered);
                collect_from_expr(value, discovered);
            }
            TypedExprKind::Match { subject, arms } => {
                collect_from_expr(subject, discovered);
                for arm in arms {
                    if let Some(g) = &arm.guard {
                        collect_from_expr(g, discovered);
                    }
                    collect_from_expr(&arm.body, discovered);
                }
            }
            TypedExprKind::Closure { body, .. } => collect_from_expr(body, discovered),
            TypedExprKind::Assert { condition, message } => {
                collect_from_expr(condition, discovered);
                if let Some(m) = message {
                    collect_from_expr(m, discovered);
                }
            }
            TypedExprKind::RecordCreate { fields, .. } => {
                for (_, e) in fields {
                    collect_from_expr(e, discovered);
                }
            }
            TypedExprKind::TupleLiteral { elements } => {
                for e in elements {
                    collect_from_expr(e, discovered);
                }
            }
            TypedExprKind::RecordWith {
                object, overrides, ..
            } => {
                collect_from_expr(object, discovered);
                for (_, _, e) in overrides {
                    collect_from_expr(e, discovered);
                }
            }
            TypedExprKind::LetDestructure { value, .. } => collect_from_expr(value, discovered),
            TypedExprKind::InterfaceObjectCoerce { inner, .. }
            | TypedExprKind::TemplateInterfaceObjectCoerce { inner, .. }
            | TypedExprKind::InterfaceObjectUpcast { inner } => {
                collect_from_expr(inner, discovered)
            }
            TypedExprKind::ImplFunctionCall { args, .. } => {
                args.iter().for_each(|a| collect_from_expr(a, discovered));
            }
            TypedExprKind::ExtFunctionCall { args, .. } => {
                args.iter().for_each(|a| collect_from_expr(a, discovered));
            }
            TypedExprKind::ForLoop { iterable, body, .. } => {
                collect_from_expr(iterable, discovered);
                collect_from_expr(body, discovered);
            }
            TypedExprKind::AsyncBlock { body, .. } => {
                collect_from_expr(body, discovered);
            }
            TypedExprKind::Try { operand, .. } => collect_from_expr(operand, discovered),
            TypedExprKind::Await { operand, .. } => collect_from_expr(operand, discovered),
            _ => {} // Literals, refs, break, continue
        }
    }

    fn collect_from_type(ty: &Type, discovered: &mut BTreeMap<MangledName, (Fqn, Vec<Type>)>) {
        if let Type::GenericClass { fqn, type_args, .. } = ty
            && !type_args.iter().any(|(_, t)| t.contains_type_parameter())
        {
            let plain_args: Vec<Type> = type_args.iter().map(|(_, t)| t.clone()).collect();
            let key = MangledName::for_function(fqn, &plain_args);
            discovered
                .entry(key)
                .or_insert_with(|| (fqn.clone(), plain_args));
        }
        // Recurse into type arguments
        match ty {
            Type::Array(inner)
            | Type::GenericNewtype {
                concrete_inner_type: inner,
                ..
            } => {
                collect_from_type(inner, discovered);
            }
            Type::Function(params, ret) => {
                for p in params {
                    collect_from_type(p, discovered);
                }
                collect_from_type(ret, discovered);
            }
            Type::GenericClass { type_args, .. } => {
                for (_, t) in type_args {
                    collect_from_type(t, discovered);
                }
            }
            Type::TupleProjection(receiver, _) => collect_from_type(receiver, discovered),
            Type::AssociatedProjection(projection) => {
                for ty in projection.types() {
                    collect_from_type(ty, discovered);
                }
            }
            Type::TupleExtend(left, right) => {
                collect_from_type(left, discovered);
                collect_from_type(right, discovered);
            }
            Type::Tuple(elems, _) => {
                for e in elems {
                    collect_from_type(e, discovered);
                }
            }
            _ => {}
        }
    }

    for func in module.functions.values() {
        collect_from_expr(&func.body, &mut discovered);
        // Also scan function signatures for GenericClass types
        for param in &func.params {
            collect_from_type(&param.ty, &mut discovered);
        }
        collect_from_type(&func.return_type, &mut discovered);
    }
    for global in module.globals.values() {
        collect_from_expr(&global.initializer, &mut discovered);
        collect_from_type(&global.ty, &mut discovered);
    }
    for test in &module.tests {
        collect_from_expr(&test.body, &mut discovered);
    }
    // Scan ClassTypeDef parent types for generic class parents
    for td in module.types.values() {
        if let TypeDef::Class(cls) = td {
            // Discover generic class parents from the resolved parent_type
            if let Some(ref parent_ty) = cls.parent_type {
                collect_from_type(parent_ty, &mut discovered);
            }
            // Also scan extends_args and fields for GenericClass references
            if let Some(ref args) = cls.extends_args {
                for arg in args {
                    collect_from_expr(arg, &mut discovered);
                }
            }
            for field in &cls.fields {
                collect_from_type(&field.ty, &mut discovered);
            }
        }
    }

    discovered
}

/// Visit all child expressions of a TypedExpr (non-recursively — just immediate children).
pub(crate) fn visit_expr_children(expr: &TypedExpr, mut f: impl FnMut(&TypedExpr)) {
    match &expr.kind {
        TypedExprKind::Block(exprs) => exprs.iter().for_each(&mut f),
        TypedExprKind::Let { value, .. } => f(value),
        TypedExprKind::FunctionCall { args, .. } => args.iter().for_each(&mut f),
        TypedExprKind::IntrinsicCall { args, .. } => args.iter().for_each(&mut f),
        TypedExprKind::If {
            condition,
            then_branch,
            else_branch,
        } => {
            f(condition);
            f(then_branch);
            if let Some(e) = else_branch {
                f(e);
            }
        }
        TypedExprKind::While { condition, body } => {
            f(condition);
            f(body);
        }
        TypedExprKind::BinaryOp { left, right, .. } => {
            f(left);
            f(right);
        }
        TypedExprKind::UnaryOp { operand, .. } => f(operand),
        TypedExprKind::Assign { value, .. } => f(value),
        TypedExprKind::Match { subject, arms } => {
            f(subject);
            for arm in arms {
                f(&arm.body);
                if let Some(g) = &arm.guard {
                    f(g);
                }
            }
        }
        TypedExprKind::Closure { body, .. } => f(body),
        TypedExprKind::ClosureCall { callee, args } => {
            f(callee);
            args.iter().for_each(&mut f);
        }
        TypedExprKind::Return { value, .. } => f(value),
        TypedExprKind::NamedCall { call: message, .. } | TypedExprKind::Panic { message } => {
            f(message)
        }
        TypedExprKind::Assert { condition, message } => {
            f(condition);
            if let Some(m) = message {
                f(m);
            }
        }
        TypedExprKind::ImplFunctionCall { args, .. } => args.iter().for_each(&mut f),
        TypedExprKind::RecordCreate { fields, .. } => fields.iter().for_each(|(_, e)| f(e)),
        TypedExprKind::TupleLiteral { elements } => elements.iter().for_each(&mut f),
        TypedExprKind::EnumCreate { args, .. } => args.iter().for_each(&mut f),
        TypedExprKind::FieldAccess { object, .. } => f(object),
        TypedExprKind::FieldAssign { object, value, .. } => {
            f(object);
            f(value);
        }
        TypedExprKind::RecordWith {
            object, overrides, ..
        } => {
            f(object);
            overrides.iter().for_each(|(_, _, e)| f(e));
        }
        TypedExprKind::ArrayLiteral { elements } => elements.iter().for_each(&mut f),
        TypedExprKind::EnumVariantRecordCreate { args, .. } => args.iter().for_each(&mut f),
        TypedExprKind::InterfaceObjectCoerce { inner, .. }
        | TypedExprKind::TemplateInterfaceObjectCoerce { inner, .. }
        | TypedExprKind::InterfaceObjectUpcast { inner } => f(inner),
        TypedExprKind::InterfaceObjectMethodCall { receiver, args, .. } => {
            f(receiver);
            args.iter().for_each(&mut f);
        }
        TypedExprKind::MethodRef { object, .. } => f(object),
        TypedExprKind::ClassNew { args, .. } => args.iter().for_each(&mut f),
        TypedExprKind::ClassStructCreate { fields, .. } => fields.iter().for_each(&mut f),
        TypedExprKind::ClassVirtualCall { object, args, .. } => {
            f(object);
            args.iter().for_each(&mut f);
        }
        TypedExprKind::ClassSuperCall { args, .. } => args.iter().for_each(&mut f),
        TypedExprKind::NewtypeCreate { value } => f(value),
        TypedExprKind::NewtypeValue { value } => f(value),
        TypedExprKind::TypeCast { value, .. } => f(value),
        TypedExprKind::TypeTest { value, .. } => f(value),
        TypedExprKind::BoxToAny { inner } => f(inner),
        TypedExprKind::GlobalAssign { value, .. } => f(value),
        TypedExprKind::ExtFunctionCall { args, .. } => args.iter().for_each(&mut f),
        TypedExprKind::LetDestructure { value, .. } => f(value),
        // Leaf nodes
        _ => {}
    }
}

/// Visit all child expressions of a TypedExpr mutably (non-recursively — just immediate children).
fn visit_expr_children_mut(expr: &mut TypedExpr, mut f: impl FnMut(&mut TypedExpr)) {
    match &mut expr.kind {
        TypedExprKind::Block(exprs) => exprs.iter_mut().for_each(&mut f),
        TypedExprKind::Let { value, .. } => f(value),
        TypedExprKind::FunctionCall { args, .. } => args.iter_mut().for_each(&mut f),
        TypedExprKind::IntrinsicCall { args, .. } => args.iter_mut().for_each(&mut f),
        TypedExprKind::If {
            condition,
            then_branch,
            else_branch,
        } => {
            f(condition);
            f(then_branch);
            if let Some(e) = else_branch {
                f(e);
            }
        }
        TypedExprKind::While { condition, body } => {
            f(condition);
            f(body);
        }
        TypedExprKind::BinaryOp { left, right, .. } => {
            f(left);
            f(right);
        }
        TypedExprKind::UnaryOp { operand, .. } => f(operand),
        TypedExprKind::Assign { value, .. } => f(value),
        TypedExprKind::Match { subject, arms } => {
            f(subject);
            for arm in arms {
                f(&mut arm.body);
                if let Some(g) = &mut arm.guard {
                    f(g);
                }
            }
        }
        TypedExprKind::Closure { body, .. } => f(body),
        TypedExprKind::ClosureCall { callee, args } => {
            f(callee);
            args.iter_mut().for_each(&mut f);
        }
        TypedExprKind::Return { value, .. } => f(value),
        TypedExprKind::NamedCall { call: message, .. } | TypedExprKind::Panic { message } => {
            f(message)
        }
        TypedExprKind::Assert { condition, message } => {
            f(condition);
            if let Some(m) = message {
                f(m);
            }
        }
        TypedExprKind::ImplFunctionCall { args, .. } => args.iter_mut().for_each(&mut f),
        TypedExprKind::RecordCreate { fields, .. } => fields.iter_mut().for_each(|(_, e)| f(e)),
        TypedExprKind::TupleLiteral { elements } => elements.iter_mut().for_each(&mut f),
        TypedExprKind::EnumCreate { args, .. } => args.iter_mut().for_each(&mut f),
        TypedExprKind::FieldAccess { object, .. } => f(object),
        TypedExprKind::FieldAssign { object, value, .. } => {
            f(object);
            f(value);
        }
        TypedExprKind::RecordWith {
            object, overrides, ..
        } => {
            f(object);
            overrides.iter_mut().for_each(|(_, _, e)| f(e));
        }
        TypedExprKind::ArrayLiteral { elements } => elements.iter_mut().for_each(&mut f),
        TypedExprKind::EnumVariantRecordCreate { args, .. } => args.iter_mut().for_each(&mut f),
        TypedExprKind::InterfaceObjectCoerce { inner, .. }
        | TypedExprKind::TemplateInterfaceObjectCoerce { inner, .. }
        | TypedExprKind::InterfaceObjectUpcast { inner } => f(inner),
        TypedExprKind::InterfaceObjectMethodCall { receiver, args, .. } => {
            f(receiver);
            args.iter_mut().for_each(&mut f);
        }
        TypedExprKind::MethodRef { object, .. } => f(object),
        TypedExprKind::ClassNew { args, .. } => args.iter_mut().for_each(&mut f),
        TypedExprKind::ClassStructCreate { fields, .. } => fields.iter_mut().for_each(&mut f),
        TypedExprKind::ClassVirtualCall { object, args, .. } => {
            f(object);
            args.iter_mut().for_each(&mut f);
        }
        TypedExprKind::ClassSuperCall { args, .. } => args.iter_mut().for_each(&mut f),
        TypedExprKind::NewtypeCreate { value } => f(value),
        TypedExprKind::NewtypeValue { value } => f(value),
        TypedExprKind::TypeCast { value, .. } => f(value),
        TypedExprKind::TypeTest { value, .. } => f(value),
        TypedExprKind::BoxToAny { inner } => f(inner),
        TypedExprKind::GlobalAssign { value, .. } => f(value),
        TypedExprKind::ExtFunctionCall { args, .. } => args.iter_mut().for_each(&mut f),
        TypedExprKind::LetDestructure { value, .. } => f(value),
        _ => {}
    }
}

pub fn ensure_vtable_functions(
    module: &mut TypedModule,
    registry: &Registry,
) -> Result<(), SpecializationError> {
    let mut rounds = SpecializationRounds::default();
    loop {
        let previous_names: BTreeSet<_> = module.functions.keys().cloned().collect();
        materialize_vtable_functions(module);
        settle_specializations(module, registry)?;
        if module.functions.len() == previous_names.len() {
            module.implement_blocks.clear();
            module.extension_blocks.clear();
            module.function_templates.clear();
            return Ok(());
        }
        // New concrete functions may require boxing or introduce more vtables.
        crate::coerce::elaborate_coercions(module, registry);
        rounds.advance_for_new_functions(module, &previous_names)?;
    }
}

fn materialize_vtable_functions(module: &mut TypedModule) {
    let impl_blocks = module.implement_blocks.clone();
    let existing: std::collections::BTreeSet<MangledName> =
        module.functions.keys().cloned().collect();
    let mut new_functions: BTreeMap<MangledName, TypedFunction> = BTreeMap::new();
    for func in module.functions.values() {
        ensure_vtable_functions_in_expr(&func.body, &impl_blocks, &mut new_functions, &existing);
    }
    for global in module.globals.values() {
        ensure_vtable_functions_in_expr(
            &global.initializer,
            &impl_blocks,
            &mut new_functions,
            &existing,
        );
    }
    for test in &module.tests {
        ensure_vtable_functions_in_expr(&test.body, &impl_blocks, &mut new_functions, &existing);
    }
    // Synthetic direct super coercions have no expression — ensure their
    // vtable entries' functions the same way.
    for syn in module.synthetic_interface_coercions.clone() {
        for (_component_mn, entries) in &syn.vtable_methods {
            for (_member_name, vtable_impl_mangled, vtable_type_args) in entries {
                if !existing.contains(vtable_impl_mangled)
                    && !new_functions.contains_key(vtable_impl_mangled)
                {
                    implement_blocks::ensure_vtable_method_function(
                        vtable_impl_mangled,
                        &syn.concrete_type,
                        vtable_type_args,
                        &impl_blocks,
                        &mut new_functions,
                        &existing,
                    );
                }
            }
        }
    }
    module.functions.extend(new_functions);
}

use crate::typechecker::types::TypedFunction;

fn ensure_vtable_functions_in_expr(
    expr: &TypedExpr,
    impl_blocks: &[TypedImplementBlock],
    new_functions: &mut BTreeMap<MangledName, TypedFunction>,
    existing: &std::collections::BTreeSet<MangledName>,
) {
    match &expr.kind {
        TypedExprKind::InterfaceObjectCoerce {
            inner,
            concrete_type,
            vtable_methods,
            ..
        } => {
            for (_component_mn, entries) in vtable_methods {
                for (_member_name, vtable_impl_mangled, vtable_type_args) in entries {
                    if !existing.contains(vtable_impl_mangled)
                        && !new_functions.contains_key(vtable_impl_mangled)
                    {
                        implement_blocks::ensure_vtable_method_function(
                            vtable_impl_mangled,
                            concrete_type,
                            vtable_type_args,
                            impl_blocks,
                            new_functions,
                            existing,
                        );
                    }
                }
            }
            ensure_vtable_functions_in_expr(inner, impl_blocks, new_functions, existing);
        }
        TypedExprKind::InterfaceObjectUpcast { inner } => {
            ensure_vtable_functions_in_expr(inner, impl_blocks, new_functions, existing);
        }
        TypedExprKind::Block(exprs) => {
            for e in exprs {
                ensure_vtable_functions_in_expr(e, impl_blocks, new_functions, existing);
            }
        }
        TypedExprKind::Let { value, .. } | TypedExprKind::Assign { value, .. } => {
            ensure_vtable_functions_in_expr(value, impl_blocks, new_functions, existing);
        }
        TypedExprKind::If {
            condition,
            then_branch,
            else_branch,
            ..
        } => {
            ensure_vtable_functions_in_expr(condition, impl_blocks, new_functions, existing);
            ensure_vtable_functions_in_expr(then_branch, impl_blocks, new_functions, existing);
            if let Some(e) = else_branch {
                ensure_vtable_functions_in_expr(e, impl_blocks, new_functions, existing);
            }
        }
        TypedExprKind::FunctionCall { args, .. }
        | TypedExprKind::IntrinsicCall { args, .. }
        | TypedExprKind::ClassNew { args, .. }
        | TypedExprKind::ClassVirtualCall { args, .. }
        | TypedExprKind::ClassSuperCall { args, .. }
        | TypedExprKind::ClosureCall { args, .. }
        | TypedExprKind::InterfaceObjectMethodCall { args, .. }
        | TypedExprKind::ExtFunctionCall { args, .. } => {
            for a in args {
                ensure_vtable_functions_in_expr(a, impl_blocks, new_functions, existing);
            }
        }
        TypedExprKind::Match { subject, arms, .. } => {
            ensure_vtable_functions_in_expr(subject, impl_blocks, new_functions, existing);
            for arm in arms {
                ensure_vtable_functions_in_expr(&arm.body, impl_blocks, new_functions, existing);
                if let Some(g) = &arm.guard {
                    ensure_vtable_functions_in_expr(g, impl_blocks, new_functions, existing);
                }
            }
        }
        TypedExprKind::Closure { body, .. }
        | TypedExprKind::Return { value: body, .. }
        | TypedExprKind::BoxToAny { inner: body, .. }
        | TypedExprKind::TypeTest { value: body, .. }
        | TypedExprKind::TypeCast { value: body, .. }
        | TypedExprKind::Panic { message: body, .. }
        | TypedExprKind::NewtypeCreate { value: body, .. }
        | TypedExprKind::NewtypeValue { value: body, .. }
        | TypedExprKind::TemplateInterfaceObjectCoerce { inner: body, .. } => {
            ensure_vtable_functions_in_expr(body, impl_blocks, new_functions, existing);
        }
        TypedExprKind::Assert { condition, message } => {
            ensure_vtable_functions_in_expr(condition, impl_blocks, new_functions, existing);
            if let Some(m) = message {
                ensure_vtable_functions_in_expr(m, impl_blocks, new_functions, existing);
            }
        }
        TypedExprKind::While { condition, body } => {
            ensure_vtable_functions_in_expr(condition, impl_blocks, new_functions, existing);
            ensure_vtable_functions_in_expr(body, impl_blocks, new_functions, existing);
        }
        TypedExprKind::BinaryOp { left, right, .. } => {
            ensure_vtable_functions_in_expr(left, impl_blocks, new_functions, existing);
            ensure_vtable_functions_in_expr(right, impl_blocks, new_functions, existing);
        }
        TypedExprKind::UnaryOp { operand, .. } => {
            ensure_vtable_functions_in_expr(operand, impl_blocks, new_functions, existing);
        }
        TypedExprKind::FieldAccess { object, .. } | TypedExprKind::FieldAssign { object, .. } => {
            ensure_vtable_functions_in_expr(object, impl_blocks, new_functions, existing);
        }
        TypedExprKind::GlobalAssign { value, .. } | TypedExprKind::LetDestructure { value, .. } => {
            ensure_vtable_functions_in_expr(value, impl_blocks, new_functions, existing);
        }
        TypedExprKind::ArrayLiteral { elements, .. } => {
            for e in elements {
                ensure_vtable_functions_in_expr(e, impl_blocks, new_functions, existing);
            }
        }
        TypedExprKind::RecordWith {
            object, overrides, ..
        } => {
            ensure_vtable_functions_in_expr(object, impl_blocks, new_functions, existing);
            for (_, _, e) in overrides {
                ensure_vtable_functions_in_expr(e, impl_blocks, new_functions, existing);
            }
        }
        TypedExprKind::ClassStructCreate { fields, .. } => {
            for f in fields {
                ensure_vtable_functions_in_expr(f, impl_blocks, new_functions, existing);
            }
        }
        TypedExprKind::RecordCreate { fields, .. } => {
            for (_, e) in fields {
                ensure_vtable_functions_in_expr(e, impl_blocks, new_functions, existing);
            }
        }
        TypedExprKind::TupleLiteral { elements } => {
            for e in elements {
                ensure_vtable_functions_in_expr(e, impl_blocks, new_functions, existing);
            }
        }
        TypedExprKind::EnumCreate { args, .. }
        | TypedExprKind::EnumVariantRecordCreate { args, .. } => {
            for a in args {
                ensure_vtable_functions_in_expr(a, impl_blocks, new_functions, existing);
            }
        }
        _ => {}
    }
}
